export interface DigitalTwinAsset {
  assetId: string;
  stationId: "maitri" | "bharati";
  name: string;
  category: "POWER" | "FUEL" | "WATER" | "HVAC" | "COMMS" | "SCIENCE" | "BUILDING" | "LOGISTICS" | "SAFETY" | "VEHICLE";
  position3D: [number, number, number];
  rotation3D?: [number, number, number];
  scale3D?: [number, number, number];
  operationalStatus: "RUNNING" | "STOPPED" | "WARNING" | "CRITICAL" | "STANDBY" | "MAINTENANCE";
  healthScore: number;
  failureProbability: number;
  rulHours: number;
  anomalyScore: number;
    readings: {},
  specifications: Record<string, string>;
  maintenance: { lastService: string; nextDueHours: number; intervalHours: number };
  systemDependencies: string[];
}

export const MAITRI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Buildings & Core Habitat
  "BLD-MAI-MAIN": {
    assetId: "BLD-MAI-MAIN",
    stationId: "maitri",
    name: "Maitri Main Station Complex",
    category: "BUILDING",
    position3D: [0, 2.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 18500,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      Structure: "U-shaped Prefabricated Composite Panels on Telescopic Steel Stilts",
      Capacity: "25 Winter-over / 65 Summer Expeditioners",
      Footprint: "45m x 35m U-plan",
      Commissioned: "26 January 1989 (38+ Years Operational)",
      Location: "Schirmacher Oasis (70°45′52″S, 11°44′03″E)",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["HVC-MAI-001", "GEN-MAI-001", "WTR-MAI-001"],
  },

  // Power Infrastructure
  "GEN-MAI-001": {
    assetId: "GEN-MAI-001",
    stationId: "maitri",
    name: "Primary Diesel Generator 1",
    category: "POWER",
    position3D: [-14.5, 1.2, -2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7200,
    anomalyScore: 0.05,
    readings: {},
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Exhaust & Coolant Hydronic Loop",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 480, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-002": {
    assetId: "GEN-MAI-002",
    stationId: "maitri",
    name: "Primary Diesel Generator 2",
    category: "POWER",
    position3D: [-14.5, 1.2, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.91,
    failureProbability: 0.05,
    rulHours: 6400,
    anomalyScore: 0.08,
    readings: {},
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Hydronic Heating Matrix",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 320, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-003": {
    assetId: "GEN-MAI-003",
    stationId: "maitri",
    name: "Standby Emergency Generator 3",
    category: "POWER",
    position3D: [-14.5, 1.2, 3.5],
    operationalStatus: "STANDBY",
    healthScore: 1.0,
    failureProbability: 0.01,
    rulHours: 12000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Model: "Cummins AMF Emergency Unit",
      Rating: "100 kVA @ 400V",
      AutoStartDelay: "< 15 seconds",
    },
    maintenance: { lastService: "2026-02-10", nextDueHours: 950, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "BAT-MAI-001": {
    assetId: "BAT-MAI-001",
    stationId: "maitri",
    name: "Battery Energy Storage Bank A (BESS)",
    category: "POWER",
    position3D: [-8.5, 1.0, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 15400,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Technology: "Lithium Iron Phosphate (LiFePO4) Modular Rack",
      Capacity: "150 kWh / 400 VDC",
      CycleCount: "1,420 cycles",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 6200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "SWG-MAI-001": {
    assetId: "SWG-MAI-001",
    stationId: "maitri",
    name: "Central Microgrid Switchgear",
    category: "POWER",
    position3D: [-11.0, 1.2, 0.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      BusbarRating: "630 A Synchronous Bus",
      ProtectiveRelays: "ABB Microprocessor Digital Protection",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Fuel Storage Farm
  "FUL-MAI-001": {
    assetId: "FUL-MAI-001",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 01",
    category: "FUEL",
    position3D: [12.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 32000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Capacity: "30,000 Liters Double-Walled Arctic Steel",
      FuelGrade: "Aviation/Polar Grade Low Pour-Point High-Cetane Diesel",
      Bunding: "110% Spill Containment Berm",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "FUL-MAI-002": {
    assetId: "FUL-MAI-002",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 02",
    category: "FUEL",
    position3D: [16.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 34000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Capacity: "30,000 Liters Insulated Tank",
      FuelGrade: "Polar Diesel ATF-Grade",
      Bunding: "Secondary Containment Sump",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "PMP-MAI-FUEL": {
    assetId: "PMP-MAI-FUEL",
    stationId: "maitri",
    name: "Fuel Transfer Pump Skid",
    category: "FUEL",
    position3D: [14.0, 0.8, 6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 8400,
    anomalyScore: 0.04,
    readings: {},
    specifications: {
      PumpType: "Positive Displacement Explosion-Proof Gear Pump",
      HeatedTrace: "Electric Trace-Heated Distribution Piping",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 1200, intervalHours: 2500 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Lake Priyadarshini Water System
  "PMP-MAI-LAKE": {
    assetId: "PMP-MAI-LAKE",
    stationId: "maitri",
    name: "Lake Priyadarshini Pump House",
    category: "WATER",
    position3D: [16.0, 0.8, -24.0],
    operationalStatus: "RUNNING",
    healthScore: 0.93,
    failureProbability: 0.04,
    rulHours: 5800,
    anomalyScore: 0.06,
    readings: {},
    specifications: {
      IntakeDepth: "Sub-Ice 4.5m Pier Penetration in Lake Priyadarshini",
      Pipeline: "450m Insulated Electrically Heated Polyethylene Pipe",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 650, intervalHours: 1500 },
    systemDependencies: ["WTR-MAI-001"],
  },

  "WTR-MAI-001": {
    assetId: "WTR-MAI-001",
    stationId: "maitri",
    name: "Priyadarshini Water Treatment Plant",
    category: "WATER",
    position3D: [10.0, 1.2, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7800,
    anomalyScore: 0.04,
    readings: {},
    specifications: {
      Process: "Dual-Stage Sand Filtration + UV Disinfection + Activated Carbon",
      OutputCapacity: "250 Liters/hour clean potable water",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 1100, intervalHours: 2000 },
    systemDependencies: ["PMP-MAI-LAKE", "BLD-MAI-MAIN"],
  },

  // Scientific, AWS & Comms
  "COM-MAI-001": {
    assetId: "COM-MAI-001",
    stationId: "maitri",
    name: "Ku-Band Satellite Ground Station Radome",
    category: "COMMS",
    position3D: [12.0, 3.5, -7.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 28000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Dish: "3.0m Ku-Band Steerable Satellite Reflector under Hydrophobic Radome",
      Function: "Real-time Telemetry, Voice, Data Link to NCPOR Goa HQ",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 5200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "AWS-MAI-001": {
    assetId: "AWS-MAI-001",
    stationId: "maitri",
    name: "Automatic Weather Station (AWS) & Radiosonde",
    category: "SCIENCE",
    position3D: [8.0, 1.5, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Sensors: "Ultrasonic Anemometer, RTD Temp Shield, Barometric Transducer",
      Radiosonde: "Helium Balloon Launch Pad for Altitude Profile & Ozone Sonde",
      LogRate: "1 Hz sampling with 1-min averaging",
    },
    maintenance: { lastService: "2026-01-08", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["COM-MAI-001"],
  },

  "RAD-MAI-MARA": {
    assetId: "RAD-MAI-MARA",
    stationId: "maitri",
    name: "MARA - Moveable Atmospheric Radar",
    category: "SCIENCE",
    position3D: [10.0, 1.2, -18.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 19800,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Type: "VHF Pulsed Doppler Atmospheric Radar (54.5 MHz)",
      Coverage: "Boundary Layer -> Troposphere -> Stratosphere -> Mesosphere",
      AntennaArray: "Ground Grid Matrix of Dipole Masts",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 3500, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "ION-MAI-CADI": {
    assetId: "ION-MAI-CADI",
    stationId: "maitri",
    name: "CADI Ionosonde (Canadian Advanced Digital)",
    category: "SCIENCE",
    position3D: [-12.0, 1.5, -20.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.03,
    rulHours: 18200,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      System: "Digital HF Ionosonde for Polar Ionospheric Sounding",
      Frequency: "1 to 30 MHz High Power Pulsed Transmission",
      Output: "Real-time Ionogram Diagnostic of Electron Density",
    },
    maintenance: { lastService: "2026-01-19", nextDueHours: 4100, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "TEC-MAI-GISTM": {
    assetId: "TEC-MAI-GISTM",
    stationId: "maitri",
    name: "GSV-4004B Scintillation & TEC Receiver",
    category: "SCIENCE",
    position3D: [14.0, 2.0, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Model: "GSV-4004B GISTM Dual-Frequency Receiver",
      Frequency: "GPS L1 (1575.42 MHz) & L2 (1227.60 MHz)",
      Purpose: "Space Weather & Polar Scintillation Monitoring",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 6000, intervalHours: 8760 },
    systemDependencies: ["COM-MAI-001"],
  },

  "MAG-MAI-IIG": {
    assetId: "MAG-MAI-IIG",
    stationId: "maitri",
    name: "IIG Geomagnetic Magnetometer Suite",
    category: "SCIENCE",
    position3D: [-18.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 30000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E (Nandadevi Hut)",
      Instruments: "DFM (Digital Fluxgate), PPM (Proton), ICM (Induction), DIM",
      Operator: "Indian Institute of Geomagnetism (IIG), Mumbai",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7500, intervalHours: 8760 },
    systemDependencies: ["HUT-MAI-NANDADEVI"],
  },

  "RIO-MAI-38": {
    assetId: "RIO-MAI-38",
    stationId: "maitri",
    name: "38.2 MHz Imaging Riometer",
    category: "SCIENCE",
    position3D: [18.0, 0.5, -18.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 26000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Type: "Imaging Relative Ionospheric Opacity Meter (Riometer)",
      Antenna: "Grid Array of Crossed Dipoles on Ground",
      Purpose: "D-region Absorption & Solar Particle Events",
    },
    maintenance: { lastService: "2026-01-26", nextDueHours: 6800, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "GEC-MAI-EFIELD": {
    assetId: "GEC-MAI-EFIELD",
    stationId: "maitri",
    name: "Global Atmospheric Electricity (GEC) Suite",
    category: "SCIENCE",
    position3D: [-16.0, 1.2, -15.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 21000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Suite: "Electric Field Mill, Long-Wire Antenna, Air-Earth Current Plate, Maxwell Wire",
      Purpose: "Global Thundercloud Circuit & Polar Electric Field",
    },
    maintenance: { lastService: "2026-01-30", nextDueHours: 5200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "SEI-MAI-001": {
    assetId: "SEI-MAI-001",
    stationId: "maitri",
    name: "Seismograph Rock Vault Station",
    category: "SCIENCE",
    position3D: [-20.0, 0.4, -8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E (Seismometer Vault in Bedrock)",
      Sensor: "Broadband 3-Component Seismometer (0 to 500 Hz)",
      Purpose: "Global Earthquake Detection & Crustal Velocity Structure",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 8000, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "GPS-MAI-GEO": {
    assetId: "GPS-MAI-GEO",
    stationId: "maitri",
    name: "Geodetic GPS Pillar Monument",
    category: "SCIENCE",
    position3D: [-19.0, 1.0, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 45000,
    anomalyScore: 0.0,
    readings: {},
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E",
      Frequency: "1176–1575 MHz (GPS L1/L2/L5 Geodetic Receiver)",
      Anchor: "Concrete Pier Mounted Directly on Pre-Cambrian Bedrock",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 9000, intervalHours: 10000 },
    systemDependencies: ["COM-MAI-001"],
  },

  "NOX-MAI-001": {
    assetId: "NOX-MAI-001",
    stationId: "maitri",
    name: "Photometric NOx Gas Analyser",
    category: "SCIENCE",
    position3D: [3.0, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 14000,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      DetectionLimit: "0.4 ppb Sensitivity",
      Method: "Ozone Gas-Phase Chemiluminescence Photometry",
      Standard: "EN-5008-1 EMC Emission Standard (15-min averages)",
    },
    maintenance: { lastService: "2026-02-02", nextDueHours: 1500, intervalHours: 4000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "AER-MAI-001": {
    assetId: "AER-MAI-001",
    stationId: "maitri",
    name: "15-Channel Laser Aerosol Spectrometer",
    category: "SCIENCE",
    position3D: [4.0, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 16500,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      SizeRange: "0.3 µm to >= 20 µm across 15 Size Bins",
      Source: "Class 3-B Laser Optical Scattering Chamber",
      Interval: "Continuous 15-minute mean averaging",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 2400, intervalHours: 5000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "AETH-MAI-001": {
    assetId: "AETH-MAI-001",
    stationId: "maitri",
    name: "7-Wavelength Multi-Spectrum Aethelometer",
    category: "SCIENCE",
    position3D: [4.5, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 18000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Wavelengths: "370, 470, 520, 590, 660, 880, 950 nm",
      Target: "Real-time Black Carbon (BC) & Organic Carbon Aerosol",
      Sampling: "Continuous Air Sample Inlet with Optical Tape Transmission",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 3100, intervalHours: 6000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "ASI-MAI-001": {
    assetId: "ASI-MAI-001",
    stationId: "maitri",
    name: "180° All-Sky Aurora Imager",
    category: "SCIENCE",
    position3D: [0.0, 4.8, -2.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Optics: "180° Fish-Eye Lens under Weatherproof Heated Glass Dome",
      Purpose: "Aurora Australis Dynamics & Airglow Imaging",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 4500, intervalHours: 8760 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "VLF-MAI-001": {
    assetId: "VLF-MAI-001",
    stationId: "maitri",
    name: "VLF Receiver Loop Antenna Array",
    category: "SCIENCE",
    position3D: [-22.0, 1.8, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 20000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Antenna: "Orthogonal Magnetic Loop Antenna on Mast",
      Target: "Whistlers, Lightning Atmospheric Impulse, Magnetosphere Waves",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 5100, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  // Scientific Lab Huts (Outdoor Named Structures)
  "HUT-MAI-NANDADEVI": {
    assetId: "HUT-MAI-NANDADEVI",
    stationId: "maitri",
    name: "Nandadevi Hut (IIG Geomagnetism)",
    category: "SCIENCE",
    position3D: [-18.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 32000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      NamedAfter: "Nanda Devi Peak, Uttarakhand",
      UsedBy: "Indian Institute of Geomagnetism (IIG)",
      Instruments: "Houses DFM, PPM, ICM, DIM Magnetometers",
      Location: "70°45′56.21″S, 11°44′10.78″E",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-TIRUVELLA": {
    assetId: "HUT-MAI-TIRUVELLA",
    stationId: "maitri",
    name: "Tiruvella Hut (GSI Geology Lab)",
    category: "SCIENCE",
    position3D: [-15.0, 1.2, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 30000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      NamedAfter: "Thiruvella, Kerala",
      UsedBy: "Geological Survey of India (GSI)",
      Purpose: "Rock Core Processing, Petrography, Geological Analysis",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 6800, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-NPL": {
    assetId: "HUT-MAI-NPL",
    stationId: "maitri",
    name: "NPL Science Hut (Atmospheric Lab)",
    category: "SCIENCE",
    position3D: [-12.0, 1.2, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 28000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      NamedAfter: "National Physical Laboratory (NPL)",
      UsedBy: "NPL Atmospheric Scientists",
      Purpose: "Ionospheric, Atmospheric Chemistry & Greenhouse Gas Research",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 6400, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-DODDABETTA": {
    assetId: "HUT-MAI-DODDABETTA",
    stationId: "maitri",
    name: "Dodda Betta Recreation Hut",
    category: "BUILDING",
    position3D: [-9.0, 1.2, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 40000,
    anomalyScore: 0.0,
    readings: {},
    specifications: {
      NamedAfter: "Dodda Betta Peak, Nilgiris, Tamil Nadu",
      Purpose: "Expedition Recreation, Rest, Indoor Games, Hot Tea/Coffee",
      Capacity: "6-8 Scientists",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 8000, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-ANNAPOORNA": {
    assetId: "HUT-MAI-ANNAPOORNA",
    stationId: "maitri",
    name: "Annapoorna Support Module",
    category: "BUILDING",
    position3D: [-6.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      NamedAfter: "Annapurna Peak, Himalayas",
      Purpose: "Multi-purpose expedition support & scientific storage",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 7500, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-GAURIPARBAT": {
    assetId: "HUT-MAI-GAURIPARBAT",
    stationId: "maitri",
    name: "Gauri Parbat Research Module",
    category: "BUILDING",
    position3D: [-3.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 34000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      NamedAfter: "Gauri Parbat Peak, Uttarakhand",
      Purpose: "Multi-purpose polar field support hut",
    },
    maintenance: { lastService: "2026-01-24", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-GIRNAR": {
    assetId: "HUT-MAI-GIRNAR",
    stationId: "maitri",
    name: "Girnar Support Module",
    category: "BUILDING",
    position3D: [0.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 36000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      NamedAfter: "Girnar, Gujarat",
      Purpose: "Multi-purpose polar support & logistics module",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 7600, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  // Vehicles & Heavy Transport Machinery Fleet
  "VEH-MAI-PBULLY": {
    assetId: "VEH-MAI-PBULLY",
    stationId: "maitri",
    name: "PistenBully Snow Groomers (Fleet of 14)",
    category: "LOGISTICS",
    position3D: [-20.0, 0.8, 8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.93,
    failureProbability: 0.04,
    rulHours: 6200,
    anomalyScore: 0.05,
    readings: {},
    specifications: {
      Model: "PistenBully PB 300 / PB 400 Tracked Crawlers (Kässbohrer, Germany)",
      Role: "Primary Antarctic Logistics & 100km Ice Shelf Convoy Supply Transport",
      Tracks: "Heavy-duty Steel-reinforced Rubber Tracks for Snow, Ice & Rock",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 250, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-SCOOTER": {
    assetId: "VEH-MAI-SCOOTER",
    stationId: "maitri",
    name: "Polar Snow Scooters (Fleet of 4)",
    category: "LOGISTICS",
    position3D: [-24.0, 0.6, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 4800,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Type: "Heavy-duty 4-Stroke Polar Snowmobiles",
      Purpose: "Fast Reconnaissance & Field Quick-Access within 25km Oasis",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 350, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-TOYOTA": {
    assetId: "VEH-MAI-TOYOTA",
    stationId: "maitri",
    name: "Toyota Arctic Truck (South Pole Special)",
    category: "LOGISTICS",
    position3D: [-18.0, 0.9, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 12000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Vehicle: "Modified Toyota Hilux Arctic Truck 44\" Tundra Tires",
      Significance: "Historic South Pole Expedition Vehicle (2010)",
      Engine: "3.0L Turbo Diesel with Engine Block Pre-Heater",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 1200, intervalHours: 3000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-XENON": {
    assetId: "VEH-MAI-XENON",
    stationId: "maitri",
    name: "Tata Xenon-XT Polar Truck",
    category: "LOGISTICS",
    position3D: [-15.0, 0.9, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 9500,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      Make: "Tata Motors Xenon-XT 4x4 Modified Pickup",
      Purpose: "Short-haul equipment and personnel transfer across rock plateau",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 800, intervalHours: 2500 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-BULLDOZER": {
    assetId: "VEH-MAI-BULLDOZER",
    stationId: "maitri",
    name: "BD-50 Heavy Earthmover Bulldozer",
    category: "LOGISTICS",
    position3D: [-22.0, 1.1, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.91,
    failureProbability: 0.05,
    rulHours: 5400,
    anomalyScore: 0.07,
    readings: {},
    specifications: {
      Model: "BEML BD-50 Heavy Tracked Bulldozer",
      Purpose: "Clearing rock debris, snow drift removal, track/helipad prep",
    },
    maintenance: { lastService: "2026-01-08", nextDueHours: 150, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-CRANE": {
    assetId: "VEH-MAI-CRANE",
    stationId: "maitri",
    name: "Mantis 50 MT Heavy Lift Cranes (5 Units)",
    category: "LOGISTICS",
    position3D: [-26.0, 1.6, 10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 8200,
    anomalyScore: 0.04,
    readings: {},
    specifications: {
      Model: "Mantis 50 MT Tracked Telescopic Boom Cranes",
      Purpose: "Container handling, heavy equipment offloading from convoy",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 450, intervalHours: 2000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-EXCAVATOR": {
    assetId: "VEH-MAI-EXCAVATOR",
    stationId: "maitri",
    name: "Tracked Hydraulic Excavator",
    category: "LOGISTICS",
    position3D: [-24.0, 1.2, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.92,
    failureProbability: 0.04,
    rulHours: 6800,
    anomalyScore: 0.05,
    readings: {},
    specifications: {
      Type: "Heavy Tracked Hydraulic Excavator",
      Purpose: "Earthworks, meltwater ditch maintenance, rock clearing",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 320, intervalHours: 1500 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "MOD-MAI-BANJARA": {
    assetId: "MOD-MAI-BANJARA",
    stationId: "maitri",
    name: "Banjara Mobile Module & Jeevan Jyoti Genset",
    category: "LOGISTICS",
    position3D: [-28.0, 1.2, 8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 15000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Module1: "'Banjara' Heated Living Module with Kitchen & Dry Toilet for Convoy Crew",
      Module2: "'Jeevan Jyoti' Portable Emergency Diesel Generator Skid",
      Tanker: "5,000 Litre (5 KL) Mobile Fuel Trailer for 100km Ice Shelf Convoy",
    },
    maintenance: { lastService: "2026-02-08", nextDueHours: 1200, intervalHours: 3000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "INC-MAI-001": {
    assetId: "INC-MAI-001",
    stationId: "maitri",
    name: "Station Vacuum & Incinerator System",
    category: "SAFETY",
    position3D: [-14.0, 1.5, 4.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 11000,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Toilets: "Electric Incinerator Toilet Network throughout Main Building",
      Compliance: "Strict Antarctic Treaty Protocol on Environmental Protection",
      WastePolicy: "100% Non-incinerable waste backloaded to Cape Town/India",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 600, intervalHours: 2000 },
    systemDependencies: ["GEN-MAI-001"],
  },
};

export const BHARATI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Main Aerodynamic Superstructure
  "BLD-BHA-MAIN": {
    assetId: "BLD-BHA-MAIN",
    stationId: "bharati",
    name: "Bharati Main Station Superstructure",
    category: "BUILDING",
    position3D: [0, 3.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 28000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Architecture: "3-Story Aerodynamic Faceted Envelope on 83 GEWI Steel Stilts",
      Containers: "134 Interconnected 20-ft ISO Shipping Container Modules",
      Capacity: "47 Winter-over & Summer Scientists (Up to 72 in Summer)",
      Footprint: "50.0m x 29.9m (164 ft x 98 ft), Height >12.2m",
      Commissioned: "18 March 2012 (31st Indian Antarctic Expedition)",
      Location: "Larsemann Hills Promontory, Prydz Bay (69°24′24″S, 76°11′14″E)",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 6500, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "HVC-BHA-001", "WTR-BHA-001"],
  },

  // Combined Heat & Power (CHP) Generation Plant
  "GEN-BHA-001": {
    assetId: "GEN-BHA-001",
    stationId: "bharati",
    name: "Primary CHP Diesel Generator 1",
    category: "POWER",
    position3D: [-12.0, 1.6, -1.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 9200,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz 3-Phase",
      FuelGrade: "Jet-A1 Kerosene Cut for -50°C Flow",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 720, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "GEN-BHA-002": {
    assetId: "GEN-BHA-002",
    stationId: "bharati",
    name: "Primary CHP Diesel Generator 2",
    category: "POWER",
    position3D: [-12.0, 1.6, 2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 8600,
    anomalyScore: 0.05,
    readings: {},
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 540, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "GEN-BHA-003": {
    assetId: "GEN-BHA-003",
    stationId: "bharati",
    name: "Standby Redundant CHP Generator 3",
    category: "POWER",
    position3D: [-12.0, 1.6, 6.0],
    operationalStatus: "STANDBY",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 14000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Redundancy: "N+1 / N+2 Automatic Auto-Start Backup Genset",
      Output: "140 kVA @ 400V 50Hz",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 1800, intervalHours: 2500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001"],
  },

  "BAT-BHA-001": {
    assetId: "BAT-BHA-001",
    stationId: "bharati",
    name: "Containerized LiFePO4 BESS Battery Array",
    category: "POWER",
    position3D: [-6.5, 1.2, 5.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 18000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Type: "Industrial LiFePO4 Containerized BESS",
      Capacity: "250 kWh / 400 VDC",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 7800, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  "SWG-BHA-001": {
    assetId: "SWG-BHA-001",
    stationId: "bharati",
    name: "Microgrid Synchronous Switchboard",
    category: "POWER",
    position3D: [-9.0, 1.4, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Automation: "Schneider PLC Microgrid Load Shedder & Frequency Synchronizer",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Coastal Sea-Water & RO Desalination System
  "PMP-BHA-SEA": {
    assetId: "PMP-BHA-SEA",
    stationId: "bharati",
    name: "Prydz Bay Coastal Seawater Pump House",
    category: "WATER",
    position3D: [6.0, 0.6, -20.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 8900,
    anomalyScore: 0.03,
    readings: {},
    specifications: {
      Intake: "Submerged Coastal Intake Crib in Prydz Bay (~50m from station)",
      SubseaPiping: "Dual Electric Heat-Traced Titanium-Reinforced Lines",
      Depth: "Subsea 4.0m Penetration below Prydz Bay landfast sea ice",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 950, intervalHours: 2000 },
    systemDependencies: ["WTR-BHA-001"],
  },

  "WTR-BHA-001": {
    assetId: "WTR-BHA-001",
    stationId: "bharati",
    name: "Reverse Osmosis (RO) Desalination Plant",
    category: "WATER",
    position3D: [3.5, 1.2, -6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 9400,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Process: "Energy Recovery Seawater Reverse Osmosis (SWRO) with Multi-Stage Pre-Filtration + UV",
      DailyOutput: "4,500 Liters/day pure potable drinking water",
      Location: "Main Building Lower Level Technical Utilities Zone",
    },
    maintenance: { lastService: "2026-02-02", nextDueHours: 1400, intervalHours: 3000 },
    systemDependencies: ["PMP-BHA-SEA", "BLD-BHA-MAIN"],
  },

  "WWTP-BHA-001": {
    assetId: "WWTP-BHA-001",
    stationId: "bharati",
    name: "3-Stage Wastewater & Sewage Treatment Plant",
    category: "WATER",
    position3D: [6.5, 1.2, -3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 11200,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Compliance: "Antarctic Treaty Madrid Protocol (Annex III) Strict Zero-Pollution Standard",
      Process: "3-Stage Filtration + Aerobic Bio-Reactor + UV Sterilization Outfall",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 1100, intervalHours: 2500 },
    systemDependencies: ["WTR-BHA-001"],
  },

  "HVC-BHA-001": {
    assetId: "HVC-BHA-001",
    stationId: "bharati",
    name: "Rooftop HVAC Air Handling & Hydronic Recovery",
    category: "HVAC",
    position3D: [0.0, 4.2, 0.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Location: "Third / Rooftop Level Sealed Mechanical Enclosure",
      HeatingSource: "100% Hydronic Heat Recovery from MAN CHP Generator Jackets & Exhaust",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 3200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Fuel Storage Farm
  "FUL-BHA-001": {
    assetId: "FUL-BHA-001",
    stationId: "bharati",
    name: "Bulk Kerosene/Diesel Tank Battery & Dispenser",
    category: "FUEL",
    position3D: [16.0, 1.8, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 38000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Capacity: "80,000 Liters in Insulated Modular Steel Cylinders",
      FuelType: "Arctic-Grade Diesel (Jet-A1 Kerosene Cut for -50°C Flow)",
      Containment: "Double Wall with Hydrocarbon Sump Sniffers & Station Feed Pipeline",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Space & Earth Observation Satcom Array (ISRO AGEOS)
  "COM-BHA-AGEOS": {
    assetId: "COM-BHA-AGEOS",
    stationId: "bharati",
    name: "ISRO AGEOS Dual 7.3m Tracking Satellite Radomes",
    category: "COMMS",
    position3D: [14.0, 4.5, -8.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 25000,
    anomalyScore: 0.0,
    readings: {},
    specifications: {
      Name: "Antarctica Ground Station for Earth Observation Satellites (AGEOS)",
      Operator: "ISRO / National Remote Sensing Centre (NRSC), Commissioned Aug 2013",
      Dishes: "Dual 7.3m High-Gain Az-El Tracking Antennas under Pressurized Radomes",
      Satellites: "Cartosat-1/2/3, Resourcesat-2/2A, Scatsat-1, OceanSat Downlink to NRSC India",
    },
    maintenance: { lastService: "2026-02-12", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  "COM-BHA-001": {
    assetId: "COM-BHA-001",
    stationId: "bharati",
    name: "Station VSAT C-Band Satellite Terminal",
    category: "COMMS",
    position3D: [-6.0, 4.2, -4.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 30000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Dish: "2.4m High-Wind Reinforced Parabolic Reflector",
      Function: "Voice, Data, Video Conferencing, Telemedicine, EPABX Link to NCPOR Headquarters",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 6500, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  // Scientific & Meteorology Observatory
  "AWS-BHA-001": {
    assetId: "AWS-BHA-001",
    stationId: "bharati",
    name: "IMD Automatic Weather Station 10m Lattice Mast",
    category: "SCIENCE",
    position3D: [-16.0, 1.8, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Operator: "India Meteorological Department (IMD), Commissioned 2015",
      Sensors: "Ultrasonic Anemometer, RTD Temperature Shield, Barometric Transducer",
      Height: "10m Freestanding Lattice Mast in Open Larsemann Hills Terrain",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["COM-BHA-001"],
  },

  "SCI-BHA-TERRACE": {
    assetId: "SCI-BHA-TERRACE",
    stationId: "bharati",
    name: "Rooftop Open Scientific Instrument Terrace",
    category: "SCIENCE",
    position3D: [8.0, 4.2, 2.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Deck: "Third Level Outdoor Platform for Atmospheric Physics & Radiation Sensors",
      Instruments: "Aethelometer, Pyranometer, Spectroradiometer",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 6000, intervalHours: 8760 },
    systemDependencies: ["BLD-BHA-MAIN"],
  },

  // Logistics & Aviation Infrastructure
  "HLP-BHA-001": {
    assetId: "HLP-BHA-001",
    stationId: "bharati",
    name: "Certified Aviation Helideck Platform",
    category: "LOGISTICS",
    position3D: [0.0, 0.6, 18.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 50000,
    anomalyScore: 0.0,
    readings: {},
    specifications: {
      Deck: "Elevated Structural Steel Helideck with Safety Netting and Tiedowns",
      Rating: "12 Metric Tons Maximum Takeoff Weight (Mil Mi-8 / Ka-32 / Bell 212 / AS350)",
      Function: "Ship-to-Shore Logistics & 100km Inland Fieldwork Helicopter Support",
    },
    maintenance: { lastService: "2026-01-30", nextDueHours: 8500, intervalHours: 8760 },
    systemDependencies: ["AWS-BHA-001"],
  },

  "VEH-BHA-PBULLY": {
    assetId: "VEH-BHA-PBULLY",
    stationId: "bharati",
    name: "PistenBully 300 / 400 Snow Groomer Fleet",
    category: "VEHICLE",
    position3D: [-20.0, 0.8, 10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 8400,
    anomalyScore: 0.02,
    readings: {},
    specifications: {
      Fleet: "3 Tracked PistenBully 300/400 Heavy Crawler Snowcats",
      Blade: "12-Way Front Hydraulic Dozer Blade & Rear Snow Tiller",
      Engine: "Mercedes-Benz OM460 LA Turbocharged Diesel (400 HP)",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 400, intervalHours: 1000 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "VEH-BHA-TOYOTA": {
    assetId: "VEH-BHA-TOYOTA",
    stationId: "bharati",
    name: "Toyota Arctic Truck Tundra Expedition Pickup",
    category: "VEHICLE",
    position3D: [-24.0, 0.8, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 12000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Vehicle: "44-Inch Ultra-Wide Low-Pressure Balloon Tires on Modified 4x4 Chassis",
      Engine: "V8 Auxiliary Engine Block Pre-Heater",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 900, intervalHours: 2500 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "VEH-BHA-SCOOTER": {
    assetId: "VEH-BHA-SCOOTER",
    stationId: "bharati",
    name: "Polar Expedition Snow Scooters / Mobiles",
    category: "VEHICLE",
    position3D: [-16.0, 0.8, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 6500,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Type: "Rotax 900 ACE Engine Heavy-Duty Utility Snowmobiles",
      Use: "Short-Range Fieldwork & Fast Personnel Transport across Larsemann Hills",
    },
    maintenance: { lastService: "2026-02-04", nextDueHours: 250, intervalHours: 1000 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "CAMP-BHA-SUMMER": {
    assetId: "CAMP-BHA-SUMMER",
    stationId: "bharati",
    name: "Tented Expedition Summer Camp & Modules",
    category: "LOGISTICS",
    position3D: [24.0, 0.8, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 15000,
    anomalyScore: 0.01,
    readings: {},
    specifications: {
      Tents: "Heavy Weatherhaven Polar Pyramid Tents + Unclad Container Storage",
      Season: "Deployed Dec–Feb to Expand Station Capacity to 72 Expeditioners",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 4000, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001"],
  },
};
