export interface DigitalTwinAsset {
  assetId: string;
  stationId: "maitri" | "bharati";
  name: string;
  category: "POWER" | "FUEL" | "WATER" | "HVAC" | "COMMS" | "SCIENCE" | "BUILDING" | "LOGISTICS" | "SAFETY" | "VEHICLE";
  position3D: [number, number, number];
  rotation3D?: [number, number, number];
  scale3D?: [number, number, number];
  operationalStatus: "RUNNING" | "STOPPED" | "WARNING" | "CRITICAL" | "STANDBY" | "MAINTENANCE";
  healthScore: number;
  failureProbability: number;
  rulHours: number;
  anomalyScore: number;
  readings: Record<string, { value: number | string; unit: string; label: string }>;
  specifications: Record<string, string>;
  maintenance: { lastService: string; nextDueHours: number; intervalHours: number };
  systemDependencies: string[];
}

export const MAITRI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Buildings & Core Habitat
  "BLD-MAI-MAIN": {
    assetId: "BLD-MAI-MAIN",
    stationId: "maitri",
    name: "Maitri Main Station Complex",
    category: "BUILDING",
    position3D: [0, 2.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 18500,
    anomalyScore: 0.03,
    readings: {
      cabinTemp: { value: 21.8, unit: "°C", label: "Internal Living Temperature" },
      relativeHumidity: { value: 38.5, unit: "%", label: "Cabin Relative Humidity" },
      powerDemand: { value: 68.5, unit: "kW", label: "Active Electrical Demand" },
      co2Level: { value: 480, unit: "ppm", label: "Air Quality CO2" },
    },
    specifications: {
      Structure: "U-shaped Prefabricated Composite Panels on Telescopic Steel Stilts",
      Capacity: "25 Winter-over / 65 Summer Expeditioners",
      Footprint: "45m x 35m U-plan",
      Commissioned: "26 January 1989 (38+ Years Operational)",
      Location: "Schirmacher Oasis (70°45′52″S, 11°44′03″E)",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["HVC-MAI-001", "GEN-MAI-001", "WTR-MAI-001"],
  },

  // Power Infrastructure
  "GEN-MAI-001": {
    assetId: "GEN-MAI-001",
    stationId: "maitri",
    name: "Primary Diesel Generator 1",
    category: "POWER",
    position3D: [-14.5, 1.2, -2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7200,
    anomalyScore: 0.05,
    readings: {
      activeLoad: { value: 78.4, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 81.6, unit: "°C", label: "Engine Coolant Temp" },
      rpm: { value: 1500, unit: "RPM", label: "Engine Shaft Speed" },
      oilPressure: { value: 4.8, unit: "bar", label: "Lube Oil Pressure" },
      fuelRate: { value: 18.4, unit: "L/h", label: "Fuel Consumption Rate" },
      vibration: { value: 2.1, unit: "mm/s", label: "Bearing Vibration Level" },
    },
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Exhaust & Coolant Hydronic Loop",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 480, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-002": {
    assetId: "GEN-MAI-002",
    stationId: "maitri",
    name: "Primary Diesel Generator 2",
    category: "POWER",
    position3D: [-14.5, 1.2, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.91,
    failureProbability: 0.05,
    rulHours: 6400,
    anomalyScore: 0.08,
    readings: {
      activeLoad: { value: 66.8, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 79.2, unit: "°C", label: "Engine Coolant Temp" },
      rpm: { value: 1500, unit: "RPM", label: "Engine Shaft Speed" },
      oilPressure: { value: 4.6, unit: "bar", label: "Lube Oil Pressure" },
      fuelRate: { value: 16.2, unit: "L/h", label: "Fuel Consumption Rate" },
      vibration: { value: 2.4, unit: "mm/s", label: "Bearing Vibration Level" },
    },
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Hydronic Heating Matrix",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 320, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-003": {
    assetId: "GEN-MAI-003",
    stationId: "maitri",
    name: "Standby Emergency Generator 3",
    category: "POWER",
    position3D: [-14.5, 1.2, 3.5],
    operationalStatus: "STANDBY",
    healthScore: 1.0,
    failureProbability: 0.01,
    rulHours: 12000,
    anomalyScore: 0.01,
    readings: {
      activeLoad: { value: 0.0, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 24.5, unit: "°C", label: "Pre-Heater Jacket Temp" },
      rpm: { value: 0, unit: "RPM", label: "Engine Shaft Speed" },
      starterBattery: { value: 27.8, unit: "V", label: "Starter Battery Voltage" },
      readiness: { value: "READY", unit: "STATE", label: "Auto-Crank Status" },
    },
    specifications: {
      Model: "Cummins AMF Emergency Unit",
      Rating: "100 kVA @ 400V",
      AutoStartDelay: "< 15 seconds",
    },
    maintenance: { lastService: "2026-02-10", nextDueHours: 950, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "BAT-MAI-001": {
    assetId: "BAT-MAI-001",
    stationId: "maitri",
    name: "Battery Energy Storage Bank A (BESS)",
    category: "POWER",
    position3D: [-8.5, 1.0, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 15400,
    anomalyScore: 0.02,
    readings: {
      soc: { value: 88.5, unit: "%", label: "State of Charge" },
      busVoltage: { value: 402.4, unit: "V", label: "DC Bus Voltage" },
      internalTemp: { value: 21.2, unit: "°C", label: "Cell Array Temperature" },
      chargeRate: { value: 4.5, unit: "kW", label: "Float Charge Power" },
    },
    specifications: {
      Technology: "Lithium Iron Phosphate (LiFePO4) Modular Rack",
      Capacity: "150 kWh / 400 VDC",
      CycleCount: "1,420 cycles",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 6200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "SWG-MAI-001": {
    assetId: "SWG-MAI-001",
    stationId: "maitri",
    name: "Central Microgrid Switchgear",
    category: "POWER",
    position3D: [-11.0, 1.2, 0.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {
      frequency: { value: 50.02, unit: "Hz", label: "Grid Synchronized Frequency" },
      totalGeneration: { value: 145.2, unit: "kW", label: "Total Active Generation" },
      totalLoad: { value: 110.0, unit: "kW", label: "Total Station Base Load" },
      powerFactor: { value: 0.94, unit: "PF", label: "System Power Factor" },
    },
    specifications: {
      BusbarRating: "630 A Synchronous Bus",
      ProtectiveRelays: "ABB Microprocessor Digital Protection",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Fuel Storage Farm
  "FUL-MAI-001": {
    assetId: "FUL-MAI-001",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 01",
    category: "FUEL",
    position3D: [12.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 32000,
    anomalyScore: 0.02,
    readings: {
      volumeLiters: { value: 24500, unit: "L", label: "Current Fuel Volume" },
      fillPercent: { value: 81.6, unit: "%", label: "Tank Fill Level" },
      fuelTemp: { value: -12.4, unit: "°C", label: "Internal Fuel Temperature" },
      daysRunway: { value: 65, unit: "Days", label: "Tank Estimated Runway" },
    },
    specifications: {
      Capacity: "30,000 Liters Double-Walled Arctic Steel",
      FuelGrade: "Aviation/Polar Grade Low Pour-Point High-Cetane Diesel",
      Bunding: "110% Spill Containment Berm",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "FUL-MAI-002": {
    assetId: "FUL-MAI-002",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 02",
    category: "FUEL",
    position3D: [16.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 34000,
    anomalyScore: 0.01,
    readings: {
      volumeLiters: { value: 20500, unit: "L", label: "Current Fuel Volume" },
      fillPercent: { value: 68.3, unit: "%", label: "Tank Fill Level" },
      fuelTemp: { value: -13.1, unit: "°C", label: "Internal Fuel Temperature" },
      daysRunway: { value: 55, unit: "Days", label: "Tank Estimated Runway" },
    },
    specifications: {
      Capacity: "30,000 Liters Insulated Tank",
      FuelGrade: "Polar Diesel ATF-Grade",
      Bunding: "Secondary Containment Sump",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "PMP-MAI-FUEL": {
    assetId: "PMP-MAI-FUEL",
    stationId: "maitri",
    name: "Fuel Transfer Pump Skid",
    category: "FUEL",
    position3D: [14.0, 0.8, 6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 8400,
    anomalyScore: 0.04,
    readings: {
      transferRate: { value: 34.5, unit: "L/min", label: "Active Fuel Flow Rate" },
      linePressure: { value: 3.2, unit: "bar", label: "Supply Line Pressure" },
      motorTemp: { value: 38.5, unit: "°C", label: "Pump Motor Temperature" },
    },
    specifications: {
      PumpType: "Positive Displacement Explosion-Proof Gear Pump",
      HeatedTrace: "Electric Trace-Heated Distribution Piping",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 1200, intervalHours: 2500 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Lake Priyadarshini Water System
  "PMP-MAI-LAKE": {
    assetId: "PMP-MAI-LAKE",
    stationId: "maitri",
    name: "Lake Priyadarshini Pump House",
    category: "WATER",
    position3D: [-6.0, 0.8, -16.0],
    operationalStatus: "RUNNING",
    healthScore: 0.93,
    failureProbability: 0.04,
    rulHours: 5800,
    anomalyScore: 0.06,
    readings: {
      intakeFlow: { value: 160.0, unit: "L/h", label: "Meltwater Intake Flow" },
      lakeWaterTemp: { value: 1.4, unit: "°C", label: "Sub-Ice Water Temperature" },
      pipeTraceTemp: { value: 8.5, unit: "°C", label: "Heated Pipeline Trace Temp" },
      intakePressure: { value: 4.1, unit: "bar", label: "Intake Line Pressure" },
    },
    specifications: {
      IntakeDepth: "Sub-Ice 4.5m Pier Penetration in Lake Priyadarshini",
      Pipeline: "450m Insulated Electrically Heated Polyethylene Pipe",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 650, intervalHours: 1500 },
    systemDependencies: ["WTR-MAI-001"],
  },

  "WTR-MAI-001": {
    assetId: "WTR-MAI-001",
    stationId: "maitri",
    name: "Priyadarshini Water Treatment Plant",
    category: "WATER",
    position3D: [-5.0, 1.2, -6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7800,
    anomalyScore: 0.04,
    readings: {
      treatedVolume: { value: 8200, unit: "L", label: "Storage Buffer Volume" },
      filtrationPressure: { value: 3.8, unit: "bar", label: "Filter Differential Pressure" },
      turbidity: { value: 0.18, unit: "NTU", label: "Water Purity Turbidity" },
      dailyConsumption: { value: 1200, unit: "L/day", label: "Station Daily Consumption" },
    },
    specifications: {
      Process: "Dual-Stage Sand Filtration + UV Disinfection + Activated Carbon",
      OutputCapacity: "250 Liters/hour clean potable water",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 1100, intervalHours: 2000 },
    systemDependencies: ["PMP-MAI-LAKE", "BLD-MAI-MAIN"],
  },

  // Scientific, AWS & Comms
  "AWS-MAI-001": {
    assetId: "AWS-MAI-001",
    stationId: "maitri",
    name: "Automatic Weather Station (AWS) & Radiosonde",
    category: "SCIENCE",
    position3D: [8.0, 1.5, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {
      ambientTemp: { value: -25.2, unit: "°C", label: "Ambient Air Temperature" },
      windSpeed: { value: 28.5, unit: "km/h", label: "Sustained Wind Velocity" },
      windGust: { value: 42.0, unit: "km/h", label: "Peak Gust Speed" },
      windDirection: { value: "ESE (115°)", unit: "DIR", label: "Wind Azimuth" },
      barometricPressure: { value: 984.2, unit: "hPa", label: "Barometric Pressure" },
      solarRadiation: { value: 180, unit: "W/m²", label: "Downwelling Solar Flux" },
    },
    specifications: {
      Sensors: "Ultrasonic Anemometer, RTD Temp Shield, Barometric Transducer",
      Radiosonde: "Helium Balloon Launch Pad for Altitude Profile & Ozone Sonde",
      LogRate: "1 Hz sampling with 1-min averaging",
    },
    maintenance: { lastService: "2026-01-08", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["COM-MAI-001"],
  },

  "RAD-MAI-MARA": {
    assetId: "RAD-MAI-MARA",
    stationId: "maitri",
    name: "MARA - Moveable Atmospheric Radar",
    category: "SCIENCE",
    position3D: [10.0, 1.2, -18.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 19800,
    anomalyScore: 0.02,
    readings: {
      frequency: { value: 54.5, unit: "MHz", label: "Operating Radar Frequency" },
      windProfileVelocity: { value: 18.2, unit: "m/s", label: "Tropospheric Wind Speed" },
      turbulenceIntensity: { value: 0.42, unit: "dBz", label: "Atmospheric Turbulence" },
      layerHeight: { value: 12.5, unit: "km", label: "Tropopause Boundary Altitude" },
    },
    specifications: {
      Type: "VHF Pulsed Doppler Atmospheric Radar (54.5 MHz)",
      Coverage: "Boundary Layer -> Troposphere -> Stratosphere -> Mesosphere",
      AntennaArray: "Ground Grid Matrix of Dipole Masts",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 3500, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "ION-MAI-CADI": {
    assetId: "ION-MAI-CADI",
    stationId: "maitri",
    name: "CADI Ionosonde (Canadian Advanced Digital)",
    category: "SCIENCE",
    position3D: [-12.0, 1.5, -20.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.03,
    rulHours: 18200,
    anomalyScore: 0.03,
    readings: {
      foF2: { value: 4.85, unit: "MHz", label: "Critical F2 Layer Frequency" },
      virtualHeight: { value: 245, unit: "km", label: "Ionosphere Reflection Height" },
      pulsePower: { value: 600, unit: "W", label: "Transmitter Peak Pulse Power" },
      sweepRange: { value: "1-30", unit: "MHz", label: "RF Sounding Sweep Range" },
    },
    specifications: {
      System: "Digital HF Ionosonde for Polar Ionospheric Sounding",
      Frequency: "1 to 30 MHz High Power Pulsed Transmission",
      Output: "Real-time Ionogram Diagnostic of Electron Density",
    },
    maintenance: { lastService: "2026-01-19", nextDueHours: 4100, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "TEC-MAI-GISTM": {
    assetId: "TEC-MAI-GISTM",
    stationId: "maitri",
    name: "GSV-4004B Scintillation & TEC Receiver",
    category: "SCIENCE",
    position3D: [14.0, 2.0, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {
      tecValue: { value: 14.2, unit: "TECU", label: "Total Electron Content" },
      s4Index: { value: 0.18, unit: "S4", label: "Amplitude Scintillation Index" },
      sigmaPhi: { value: 0.08, unit: "rad", label: "Phase Scintillation Index" },
      snrL1: { value: 46.5, unit: "dB-Hz", label: "GPS L1 Signal-to-Noise Ratio" },
    },
    specifications: {
      Model: "GSV-4004B GISTM Dual-Frequency Receiver",
      Frequency: "GPS L1 (1575.42 MHz) & L2 (1227.60 MHz)",
      Purpose: "Space Weather & Polar Scintillation Monitoring",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 6000, intervalHours: 8760 },
    systemDependencies: ["COM-MAI-001"],
  },

  "MAG-MAI-IIG": {
    assetId: "MAG-MAI-IIG",
    stationId: "maitri",
    name: "IIG Geomagnetic Magnetometer Suite",
    category: "SCIENCE",
    position3D: [-18.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 30000,
    anomalyScore: 0.01,
    readings: {
      magneticBx: { value: 18450, unit: "nT", label: "Magnetic Field X (North)" },
      magneticBy: { value: -2150, unit: "nT", label: "Magnetic Field Y (East)" },
      magneticBz: { value: 44200, unit: "nT", label: "Magnetic Field Z (Down)" },
      totalFieldF: { value: 47920, unit: "nT", label: "Total Magnetic Intensity F" },
      declinationD: { value: -21.4, unit: "°", label: "Magnetic Declination D" },
    },
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E (Nandadevi Hut)",
      Instruments: "DFM (Digital Fluxgate), PPM (Proton), ICM (Induction), DIM",
      Operator: "Indian Institute of Geomagnetism (IIG), Mumbai",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7500, intervalHours: 8760 },
    systemDependencies: ["HUT-MAI-NANDADEVI"],
  },

  "RIO-MAI-38": {
    assetId: "RIO-MAI-38",
    stationId: "maitri",
    name: "38.2 MHz Imaging Riometer",
    category: "SCIENCE",
    position3D: [18.0, 0.5, -18.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 26000,
    anomalyScore: 0.02,
    readings: {
      absorption: { value: 0.45, unit: "dB", label: "Cosmic Radio Absorption" },
      noiseFlux: { value: 1240, unit: "K", label: "Background Cosmic Noise Temp" },
      frequency: { value: 38.2, unit: "MHz", label: "Passive Monitoring Frequency" },
    },
    specifications: {
      Type: "Imaging Relative Ionospheric Opacity Meter (Riometer)",
      Antenna: "Grid Array of Crossed Dipoles on Ground",
      Purpose: "D-region Absorption & Solar Particle Events",
    },
    maintenance: { lastService: "2026-01-26", nextDueHours: 6800, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "GEC-MAI-EFIELD": {
    assetId: "GEC-MAI-EFIELD",
    stationId: "maitri",
    name: "Global Atmospheric Electricity (GEC) Suite",
    category: "SCIENCE",
    position3D: [-16.0, 1.2, -15.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 21000,
    anomalyScore: 0.02,
    readings: {
      electricField: { value: 112.5, unit: "V/m", label: "Fair-Weather Electric Field" },
      airEarthCurrent: { value: 2.15, unit: "pA/m²", label: "Return Current Density" },
      maxwellCurrent: { value: 1.85, unit: "pA/m²", label: "Maxwell Current Density" },
    },
    specifications: {
      Suite: "Electric Field Mill, Long-Wire Antenna, Air-Earth Current Plate, Maxwell Wire",
      Purpose: "Global Thundercloud Circuit & Polar Electric Field",
    },
    maintenance: { lastService: "2026-01-30", nextDueHours: 5200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "SEI-MAI-001": {
    assetId: "SEI-MAI-001",
    stationId: "maitri",
    name: "Seismograph Rock Vault Station",
    category: "SCIENCE",
    position3D: [-20.0, 0.4, -8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {
      groundVelocity: { value: 1.25, unit: "µm/s", label: "Ground Vibration Velocity" },
      bandwidth: { value: "0-500", unit: "Hz", label: "Seismic Frequency Range" },
      seismicEventTrigger: { value: "NORMAL", unit: "STATE", label: "Tectonic Event Monitor" },
    },
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E (Seismometer Vault in Bedrock)",
      Sensor: "Broadband 3-Component Seismometer (0 to 500 Hz)",
      Purpose: "Global Earthquake Detection & Crustal Velocity Structure",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 8000, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "GPS-MAI-GEO": {
    assetId: "GPS-MAI-GEO",
    stationId: "maitri",
    name: "Geodetic GPS Pillar Monument",
    category: "SCIENCE",
    position3D: [-19.0, 1.0, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 45000,
    anomalyScore: 0.0,
    readings: {
      latitude: { value: "-70.76683367°", unit: "DEC", label: "Precision Latitude" },
      longitude: { value: "11.73078318°", unit: "DEC", label: "Precision Longitude" },
      elevation: { value: 117.42, unit: "m", label: "Ellipsoidal Elevation" },
      crustalDrift: { value: 1.4, unit: "cm/yr", label: "Tectonic Plate Drift" },
    },
    specifications: {
      Location: "70°45′56.21″S, 11°44′10.78″E",
      Frequency: "1176–1575 MHz (GPS L1/L2/L5 Geodetic Receiver)",
      Anchor: "Concrete Pier Mounted Directly on Pre-Cambrian Bedrock",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 9000, intervalHours: 10000 },
    systemDependencies: ["COM-MAI-001"],
  },

  "NOX-MAI-001": {
    assetId: "NOX-MAI-001",
    stationId: "maitri",
    name: "Photometric NOx Gas Analyser",
    category: "SCIENCE",
    position3D: [3.0, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 14000,
    anomalyScore: 0.03,
    readings: {
      noConc: { value: 0.65, unit: "ppb", label: "Nitric Oxide (NO)" },
      no2Conc: { value: 1.12, unit: "ppb", label: "Nitrogen Dioxide (NO2)" },
      noxTotal: { value: 1.77, unit: "ppb", label: "Total NOx Concentration" },
    },
    specifications: {
      DetectionLimit: "0.4 ppb Sensitivity",
      Method: "Ozone Gas-Phase Chemiluminescence Photometry",
      Standard: "EN-5008-1 EMC Emission Standard (15-min averages)",
    },
    maintenance: { lastService: "2026-02-02", nextDueHours: 1500, intervalHours: 4000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "AER-MAI-001": {
    assetId: "AER-MAI-001",
    stationId: "maitri",
    name: "15-Channel Laser Aerosol Spectrometer",
    category: "SCIENCE",
    position3D: [4.0, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 16500,
    anomalyScore: 0.02,
    readings: {
      totalParticleCount: { value: 412, unit: "#/cm³", label: "Total Aerosol Particle Concentration" },
      pm25: { value: 0.85, unit: "µg/m³", label: "PM2.5 Mass Equivalent" },
      laserPower: { value: 98.5, unit: "%", label: "Class 3-B Laser Diode Emission" },
    },
    specifications: {
      SizeRange: "0.3 µm to >= 20 µm across 15 Size Bins",
      Source: "Class 3-B Laser Optical Scattering Chamber",
      Interval: "Continuous 15-minute mean averaging",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 2400, intervalHours: 5000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "AETH-MAI-001": {
    assetId: "AETH-MAI-001",
    stationId: "maitri",
    name: "7-Wavelength Multi-Spectrum Aethelometer",
    category: "SCIENCE",
    position3D: [4.5, 2.5, -3.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 18000,
    anomalyScore: 0.01,
    readings: {
      blackCarbon880: { value: 14.8, unit: "ng/m³", label: "Black Carbon (880nm)" },
      elementalCarbon: { value: 18.2, unit: "ng/m³", label: "Elemental Carbon Mass" },
      absorptionCoeff: { value: 0.12, unit: "Mm⁻¹", label: "Aerosol Light Absorption" },
    },
    specifications: {
      Wavelengths: "370, 470, 520, 590, 660, 880, 950 nm",
      Target: "Real-time Black Carbon (BC) & Organic Carbon Aerosol",
      Sampling: "Continuous Air Sample Inlet with Optical Tape Transmission",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 3100, intervalHours: 6000 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "ASI-MAI-001": {
    assetId: "ASI-MAI-001",
    stationId: "maitri",
    name: "180° All-Sky Aurora Imager",
    category: "SCIENCE",
    position3D: [0.0, 4.8, -2.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {
      auroraState: { value: "QUIET", unit: "STATE", label: "Aurora Australis Activity" },
      frameInterval: { value: 60, unit: "sec", label: "Full Sky Exposure Rate" },
      domeHeating: { value: 18.4, unit: "°C", label: "Fish-Eye Lens De-Ice Temp" },
    },
    specifications: {
      Optics: "180° Fish-Eye Lens under Weatherproof Heated Glass Dome",
      Purpose: "Aurora Australis Dynamics & Airglow Imaging",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 4500, intervalHours: 8760 },
    systemDependencies: ["BLD-MAI-MAIN"],
  },

  "VLF-MAI-001": {
    assetId: "VLF-MAI-001",
    stationId: "maitri",
    name: "VLF Receiver Loop Antenna Array",
    category: "SCIENCE",
    position3D: [-22.0, 1.8, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 20000,
    anomalyScore: 0.02,
    readings: {
      vlfAmplitude: { value: -78.4, unit: "dBm", label: "VLF Carrier Amplitude" },
      whistlerEvents: { value: 14, unit: "Count/hr", label: "Magnetospheric Whistlers" },
      frequencyBand: { value: "3-30", unit: "kHz", label: "VLF Operating Range" },
    },
    specifications: {
      Antenna: "Orthogonal Magnetic Loop Antenna on Mast",
      Target: "Whistlers, Lightning Atmospheric Impulse, Magnetosphere Waves",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 5100, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  // Scientific Lab Huts (Outdoor Named Structures)
  "HUT-MAI-NANDADEVI": {
    assetId: "HUT-MAI-NANDADEVI",
    stationId: "maitri",
    name: "Nandadevi Hut (IIG Geomagnetism)",
    category: "SCIENCE",
    position3D: [-18.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 32000,
    anomalyScore: 0.01,
    readings: {
      insideTemp: { value: 18.5, unit: "°C", label: "Internal Observatory Temp" },
      status: { value: "ACTIVE", unit: "STATE", label: "Magnetometer Vault Status" },
    },
    specifications: {
      NamedAfter: "Nanda Devi Peak, Uttarakhand",
      UsedBy: "Indian Institute of Geomagnetism (IIG)",
      Instruments: "Houses DFM, PPM, ICM, DIM Magnetometers",
      Location: "70°45′56.21″S, 11°44′10.78″E",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-TIRUVELLA": {
    assetId: "HUT-MAI-TIRUVELLA",
    stationId: "maitri",
    name: "Tiruvella Hut (GSI Geology Lab)",
    category: "SCIENCE",
    position3D: [-15.0, 1.2, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 30000,
    anomalyScore: 0.02,
    readings: {
      insideTemp: { value: 19.2, unit: "°C", label: "Geology Lab Temp" },
      rockCoresCount: { value: 420, unit: "Samples", label: "Stored Antarctic Rock Cores" },
    },
    specifications: {
      NamedAfter: "Thiruvella, Kerala",
      UsedBy: "Geological Survey of India (GSI)",
      Purpose: "Rock Core Processing, Petrography, Geological Analysis",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 6800, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-NPL": {
    assetId: "HUT-MAI-NPL",
    stationId: "maitri",
    name: "NPL Science Hut (Atmospheric Lab)",
    category: "SCIENCE",
    position3D: [-12.0, 1.2, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 28000,
    anomalyScore: 0.02,
    readings: {
      insideTemp: { value: 20.1, unit: "°C", label: "Lab Thermal State" },
      dataUplink: { value: "ONLINE", unit: "LINK", label: "NPL Data Telemetry" },
    },
    specifications: {
      NamedAfter: "National Physical Laboratory (NPL)",
      UsedBy: "NPL Atmospheric Scientists",
      Purpose: "Ionospheric, Atmospheric Chemistry & Greenhouse Gas Research",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 6400, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-DODDABETTA": {
    assetId: "HUT-MAI-DODDABETTA",
    stationId: "maitri",
    name: "Dodda Betta Recreation Hut",
    category: "BUILDING",
    position3D: [-9.0, 1.2, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 40000,
    anomalyScore: 0.0,
    readings: {
      insideTemp: { value: 22.5, unit: "°C", label: "Recreation Lounge Temp" },
      coffeeMachine: { value: "READY", unit: "STATE", label: "Hot Tea & Coffee Station" },
    },
    specifications: {
      NamedAfter: "Dodda Betta Peak, Nilgiris, Tamil Nadu",
      Purpose: "Expedition Recreation, Rest, Indoor Games, Hot Tea/Coffee",
      Capacity: "6-8 Scientists",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 8000, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-ANNAPOORNA": {
    assetId: "HUT-MAI-ANNAPOORNA",
    stationId: "maitri",
    name: "Annapoorna Support Module",
    category: "BUILDING",
    position3D: [-6.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {
      insideTemp: { value: 19.8, unit: "°C", label: "Module Temp" },
    },
    specifications: {
      NamedAfter: "Annapurna Peak, Himalayas",
      Purpose: "Multi-purpose expedition support & scientific storage",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 7500, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-GAURIPARBAT": {
    assetId: "HUT-MAI-GAURIPARBAT",
    stationId: "maitri",
    name: "Gauri Parbat Research Module",
    category: "BUILDING",
    position3D: [-3.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 34000,
    anomalyScore: 0.01,
    readings: {
      insideTemp: { value: 20.4, unit: "°C", label: "Module Temp" },
    },
    specifications: {
      NamedAfter: "Gauri Parbat Peak, Uttarakhand",
      Purpose: "Multi-purpose polar field support hut",
    },
    maintenance: { lastService: "2026-01-24", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HUT-MAI-GIRNAR": {
    assetId: "HUT-MAI-GIRNAR",
    stationId: "maitri",
    name: "Girnar Support Module",
    category: "BUILDING",
    position3D: [0.0, 1.2, -10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 36000,
    anomalyScore: 0.01,
    readings: {
      insideTemp: { value: 20.0, unit: "°C", label: "Module Temp" },
    },
    specifications: {
      NamedAfter: "Girnar, Gujarat",
      Purpose: "Multi-purpose polar support & logistics module",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 7600, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  // Vehicles & Heavy Transport Machinery Fleet
  "VEH-MAI-PBULLY": {
    assetId: "VEH-MAI-PBULLY",
    stationId: "maitri",
    name: "PistenBully Snow Groomers (Fleet of 14)",
    category: "LOGISTICS",
    position3D: [-20.0, 0.8, 8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.93,
    failureProbability: 0.04,
    rulHours: 6200,
    anomalyScore: 0.05,
    readings: {
      activeFleetCount: { value: 14, unit: "Units", label: "Stationed PistenBullies" },
      operationalStatus: { value: "12 ACTIVE / 2 MAINT", unit: "STATE", label: "Fleet Availability" },
      avgFuelCons: { value: 24.5, unit: "L/hr", label: "Traverse Fuel Burn Rate" },
      engineTemp: { value: 85.0, unit: "°C", label: "Track Drive Hydraulic Temp" },
    },
    specifications: {
      Model: "PistenBully PB 300 / PB 400 Tracked Crawlers (Kässbohrer, Germany)",
      Role: "Primary Antarctic Logistics & 100km Ice Shelf Convoy Supply Transport",
      Tracks: "Heavy-duty Steel-reinforced Rubber Tracks for Snow, Ice & Rock",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 250, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-SCOOTER": {
    assetId: "VEH-MAI-SCOOTER",
    stationId: "maitri",
    name: "Polar Snow Scooters (Fleet of 4)",
    category: "LOGISTICS",
    position3D: [-24.0, 0.6, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 4800,
    anomalyScore: 0.02,
    readings: {
      scooterCount: { value: 4, unit: "Units", label: "Snowmobiles Count" },
      fuelTank: { value: 92, unit: "%", label: "Average Fuel Reserve" },
    },
    specifications: {
      Type: "Heavy-duty 4-Stroke Polar Snowmobiles",
      Purpose: "Fast Reconnaissance & Field Quick-Access within 25km Oasis",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 350, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-TOYOTA": {
    assetId: "VEH-MAI-TOYOTA",
    stationId: "maitri",
    name: "Toyota Arctic Truck (South Pole Special)",
    category: "LOGISTICS",
    position3D: [-18.0, 0.9, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 12000,
    anomalyScore: 0.02,
    readings: {
      odometer: { value: 14850, unit: "km", label: "Polar Distance Driven" },
      tirePressure: { value: 0.8, unit: "bar", label: "Tundra Low-Pressure Floatation" },
    },
    specifications: {
      Vehicle: "Modified Toyota Hilux Arctic Truck 44\" Tundra Tires",
      Significance: "Historic South Pole Expedition Vehicle (2010)",
      Engine: "3.0L Turbo Diesel with Engine Block Pre-Heater",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 1200, intervalHours: 3000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-XENON": {
    assetId: "VEH-MAI-XENON",
    stationId: "maitri",
    name: "Tata Xenon-XT Polar Truck",
    category: "LOGISTICS",
    position3D: [-15.0, 0.9, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 9500,
    anomalyScore: 0.03,
    readings: {
      status: { value: "OPERATIONAL", unit: "STATE", label: "Truck Readiness" },
    },
    specifications: {
      Make: "Tata Motors Xenon-XT 4x4 Modified Pickup",
      Purpose: "Short-haul equipment and personnel transfer across rock plateau",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 800, intervalHours: 2500 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-BULLDOZER": {
    assetId: "VEH-MAI-BULLDOZER",
    stationId: "maitri",
    name: "BD-50 Heavy Earthmover Bulldozer",
    category: "LOGISTICS",
    position3D: [-22.0, 1.1, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.91,
    failureProbability: 0.05,
    rulHours: 5400,
    anomalyScore: 0.07,
    readings: {
      hydraulicPressure: { value: 185, unit: "bar", label: "Blade Hydraulics Pressure" },
      engineHours: { value: 3420, unit: "hr", label: "Cumulative Operating Hours" },
    },
    specifications: {
      Model: "BEML BD-50 Heavy Tracked Bulldozer",
      Purpose: "Clearing rock debris, snow drift removal, track/helipad prep",
    },
    maintenance: { lastService: "2026-01-08", nextDueHours: 150, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-CRANE": {
    assetId: "VEH-MAI-CRANE",
    stationId: "maitri",
    name: "Mantis 50 MT Heavy Lift Cranes (5 Units)",
    category: "LOGISTICS",
    position3D: [-26.0, 1.6, 10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 8200,
    anomalyScore: 0.04,
    readings: {
      craneCount: { value: 5, unit: "Units", label: "Stationed Cranes" },
      maxLiftCapacity: { value: 50, unit: "MT", label: "Rated Metric Ton Lift Capacity" },
    },
    specifications: {
      Model: "Mantis 50 MT Tracked Telescopic Boom Cranes",
      Purpose: "Container handling, heavy equipment offloading from convoy",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 450, intervalHours: 2000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "VEH-MAI-EXCAVATOR": {
    assetId: "VEH-MAI-EXCAVATOR",
    stationId: "maitri",
    name: "Tracked Hydraulic Excavator",
    category: "LOGISTICS",
    position3D: [-24.0, 1.2, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.92,
    failureProbability: 0.04,
    rulHours: 6800,
    anomalyScore: 0.05,
    readings: {
      bucketCapacity: { value: 1.2, unit: "m³", label: "Bucket Debris Volume" },
    },
    specifications: {
      Type: "Heavy Tracked Hydraulic Excavator",
      Purpose: "Earthworks, meltwater ditch maintenance, rock clearing",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 320, intervalHours: 1500 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "MOD-MAI-BANJARA": {
    assetId: "MOD-MAI-BANJARA",
    stationId: "maitri",
    name: "Banjara Mobile Module & Jeevan Jyoti Genset",
    category: "LOGISTICS",
    position3D: [-28.0, 1.2, 8.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 15000,
    anomalyScore: 0.01,
    readings: {
      mobileFuelCapacity: { value: 5000, unit: "L", label: "5 KL Convoy Fuel Trailer" },
      livingCabinTemp: { value: 21.0, unit: "°C", label: "Banjara Living Quarters Temp" },
      jeevanJyotiKw: { value: 15.0, unit: "kW", label: "Jeevan Jyoti Mobile Power" },
    },
    specifications: {
      Module1: "'Banjara' Heated Living Module with Kitchen & Dry Toilet for Convoy Crew",
      Module2: "'Jeevan Jyoti' Portable Emergency Diesel Generator Skid",
      Tanker: "5,000 Litre (5 KL) Mobile Fuel Trailer for 100km Ice Shelf Convoy",
    },
    maintenance: { lastService: "2026-02-08", nextDueHours: 1200, intervalHours: 3000 },
    systemDependencies: ["FUL-MAI-001"],
  },

  "INC-MAI-001": {
    assetId: "INC-MAI-001",
    stationId: "maitri",
    name: "Station Vacuum & Incinerator System",
    category: "SAFETY",
    position3D: [-14.0, 1.5, 4.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 11000,
    anomalyScore: 0.02,
    readings: {
      chamberTemp: { value: 850, unit: "°C", label: "Incinerator Burn Chamber Temp" },
      ashOutput: { value: 1.2, unit: "kg/day", label: "Sterile Ash Waste" },
      liquidDischarge: { value: 0, unit: "L", label: "Zero Environmental Liquid Discharge" },
    },
    specifications: {
      Toilets: "Electric Incinerator Toilet Network throughout Main Building",
      Compliance: "Strict Antarctic Treaty Protocol on Environmental Protection",
      WastePolicy: "100% Non-incinerable waste backloaded to Cape Town/India",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 600, intervalHours: 2000 },
    systemDependencies: ["GEN-MAI-001"],
  },
};

export const BHARATI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Main Aerodynamic Superstructure
  "BLD-BHA-MAIN": {
    assetId: "BLD-BHA-MAIN",
    stationId: "bharati",
    name: "Bharati Main Station Superstructure",
    category: "BUILDING",
    position3D: [0, 3.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 28000,
    anomalyScore: 0.01,
    readings: {
      cabinTemp: { value: 22.4, unit: "°C", label: "Internal Living Quarters Temp" },
      relativeHumidity: { value: 42.0, unit: "%", label: "Indoor Relative Humidity" },
      totalBaseLoad: { value: 135.0, unit: "kW", label: "Station Electrical Load" },
      buildingPressure: { value: "+12", unit: "Pa", label: "Positive Air Ingress Pressure" },
      windLoad: { value: 2.6, unit: "kPa", label: "Facade Dynamic Wind Pressure" },
    },
    specifications: {
      Architecture: "3-Story Aerodynamic Faceted Envelope on 83 GEWI Steel Stilts",
      Containers: "134 Interconnected 20-ft ISO Shipping Container Modules",
      Capacity: "47 Winter-over & Summer Scientists (Up to 72 in Summer)",
      Footprint: "50.0m x 29.9m (164 ft x 98 ft), Height >12.2m",
      Commissioned: "18 March 2012 (31st Indian Antarctic Expedition)",
      Location: "Larsemann Hills Promontory, Prydz Bay (69°24′24″S, 76°11′14″E)",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 6500, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "HVC-BHA-001", "WTR-BHA-001"],
  },

  // Combined Heat & Power (CHP) Generation Plant
  "GEN-BHA-001": {
    assetId: "GEN-BHA-001",
    stationId: "bharati",
    name: "Primary CHP Diesel Generator 1",
    category: "POWER",
    position3D: [-12.0, 1.6, -1.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 9200,
    anomalyScore: 0.03,
    readings: {
      electricalPower: { value: 92.4, unit: "kW", label: "Active Electrical Generation" },
      thermalOutput: { value: 112.0, unit: "kW", label: "Captured Hydronic Heat Output" },
      coolantTemp: { value: 80.4, unit: "°C", label: "CHP Jacket Coolant Temp" },
      exhaustTemp: { value: 340.0, unit: "°C", label: "Exhaust Heat Exchanger Inlet" },
      fuelFlowRate: { value: 21.2, unit: "L/h", label: "Fuel Consumption Rate" },
    },
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz 3-Phase",
      FuelGrade: "Jet-A1 Kerosene Cut for -50°C Flow",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 720, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "GEN-BHA-002": {
    assetId: "GEN-BHA-002",
    stationId: "bharati",
    name: "Primary CHP Diesel Generator 2",
    category: "POWER",
    position3D: [-12.0, 1.6, 2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 8600,
    anomalyScore: 0.05,
    readings: {
      electricalPower: { value: 88.1, unit: "kW", label: "Active Electrical Generation" },
      thermalOutput: { value: 105.5, unit: "kW", label: "Captured Hydronic Heat Output" },
      coolantTemp: { value: 81.2, unit: "°C", label: "CHP Jacket Coolant Temp" },
      fuelFlowRate: { value: 20.4, unit: "L/h", label: "Fuel Consumption Rate" },
    },
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 540, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "GEN-BHA-003": {
    assetId: "GEN-BHA-003",
    stationId: "bharati",
    name: "Standby Redundant CHP Generator 3",
    category: "POWER",
    position3D: [-12.0, 1.6, 6.0],
    operationalStatus: "STANDBY",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 14000,
    anomalyScore: 0.01,
    readings: {
      electricalPower: { value: 0.0, unit: "kW", label: "Active Electrical Generation" },
      thermalOutput: { value: 0.0, unit: "kW", label: "Captured Hydronic Heat Output" },
      coolantTemp: { value: 24.0, unit: "°C", label: "Standby Jacket Heater Temp" },
    },
    specifications: {
      Redundancy: "N+1 / N+2 Automatic Auto-Start Backup Genset",
      Output: "140 kVA @ 400V 50Hz",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 1800, intervalHours: 2500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001"],
  },

  "BAT-BHA-001": {
    assetId: "BAT-BHA-001",
    stationId: "bharati",
    name: "Containerized LiFePO4 BESS Battery Array",
    category: "POWER",
    position3D: [-6.5, 1.2, 5.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 18000,
    anomalyScore: 0.01,
    readings: {
      soc: { value: 94.2, unit: "%", label: "State of Charge" },
      dcBusVoltage: { value: 408.0, unit: "V", label: "BESS DC Bus Voltage" },
      temperature: { value: 23.0, unit: "°C", label: "Battery Enclosure Temp" },
      healthCapacity: { value: 99.1, unit: "%", label: "Retained SOH Capacity" },
    },
    specifications: {
      Type: "Industrial LiFePO4 Containerized BESS",
      Capacity: "250 kWh / 400 VDC",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 7800, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  "SWG-BHA-001": {
    assetId: "SWG-BHA-001",
    stationId: "bharati",
    name: "Microgrid Synchronous Switchboard",
    category: "POWER",
    position3D: [-9.0, 1.4, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {
      totalGenerationKw: { value: 180.5, unit: "kW", label: "Total Active Power" },
      totalDemandKw: { value: 135.0, unit: "kW", label: "Total Station Consumption" },
      gridHz: { value: 50.01, unit: "Hz", label: "System Frequency" },
      reserveMarginKw: { value: 45.5, unit: "kW", label: "Spinning Reserve Margin" },
    },
    specifications: {
      Automation: "Schneider PLC Microgrid Load Shedder & Frequency Synchronizer",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Coastal Sea-Water & RO Desalination System
  "PMP-BHA-SEA": {
    assetId: "PMP-BHA-SEA",
    stationId: "bharati",
    name: "Prydz Bay Coastal Seawater Pump House",
    category: "WATER",
    position3D: [6.0, 0.6, -20.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 8900,
    anomalyScore: 0.03,
    readings: {
      seawaterFlow: { value: 420.0, unit: "L/h", label: "Raw Seawater Intake Flow" },
      seawaterTemp: { value: -1.6, unit: "°C", label: "Prydz Bay Seawater Temp" },
      intakePressure: { value: 5.2, unit: "bar", label: "High-Pressure Delivery" },
      salinityTDS: { value: 34500, unit: "ppm", label: "Seawater Salinity TDS" },
    },
    specifications: {
      Intake: "Submerged Coastal Intake Crib in Prydz Bay (~50m from station)",
      SubseaPiping: "Dual Electric Heat-Traced Titanium-Reinforced Lines",
      Depth: "Subsea 4.0m Penetration below Prydz Bay landfast sea ice",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 950, intervalHours: 2000 },
    systemDependencies: ["WTR-BHA-001"],
  },

  "WTR-BHA-001": {
    assetId: "WTR-BHA-001",
    stationId: "bharati",
    name: "Reverse Osmosis (RO) Desalination Plant",
    category: "WATER",
    position3D: [3.5, 1.2, -6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 9400,
    anomalyScore: 0.02,
    readings: {
      permeateFlow: { value: 185.0, unit: "L/h", label: "Freshwater Production Rate" },
      storageVolume: { value: 12500, unit: "L", label: "Potable Water Reservoir Volume" },
      membranePressure: { value: 58.4, unit: "bar", label: "RO High-Pressure Membrane" },
      productTds: { value: 85, unit: "ppm", label: "Potable Mineralization Purity" },
    },
    specifications: {
      Process: "Energy Recovery Seawater Reverse Osmosis (SWRO) with Multi-Stage Pre-Filtration + UV",
      DailyOutput: "4,500 Liters/day pure potable drinking water",
      Location: "Main Building Lower Level Technical Utilities Zone",
    },
    maintenance: { lastService: "2026-02-02", nextDueHours: 1400, intervalHours: 3000 },
    systemDependencies: ["PMP-BHA-SEA", "BLD-BHA-MAIN"],
  },

  "WWTP-BHA-001": {
    assetId: "WWTP-BHA-001",
    stationId: "bharati",
    name: "3-Stage Wastewater & Sewage Treatment Plant",
    category: "WATER",
    position3D: [6.5, 1.2, -3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 11200,
    anomalyScore: 0.02,
    readings: {
      treatmentFlow: { value: 140.0, unit: "L/h", label: "Active Wastewater Flow" },
      effluentTurbidity: { value: 0.12, unit: "NTU", label: "Effluent Purity Index" },
      stage3BioFilter: { value: 98.4, unit: "%", label: "Biological Digestion Efficiency" },
    },
    specifications: {
      Compliance: "Antarctic Treaty Madrid Protocol (Annex III) Strict Zero-Pollution Standard",
      Process: "3-Stage Filtration + Aerobic Bio-Reactor + UV Sterilization Outfall",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 1100, intervalHours: 2500 },
    systemDependencies: ["WTR-BHA-001"],
  },

  "HVC-BHA-001": {
    assetId: "HVC-BHA-001",
    stationId: "bharati",
    name: "Rooftop HVAC Air Handling & Hydronic Recovery",
    category: "HVAC",
    position3D: [0.0, 4.2, 0.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {
      supplyAirTemp: { value: 21.5, unit: "°C", label: "Conditioned Supply Air Temp" },
      returnAirTemp: { value: 19.8, unit: "°C", label: "Return Duct Air Temp" },
      outsideAirTemp: { value: -22.4, unit: "°C", label: "Outside Ambient Air" },
      heatExchangerDuty: { value: 185.0, unit: "kW", label: "Recovered Hydronic Thermal Heat" },
    },
    specifications: {
      Location: "Third / Rooftop Level Sealed Mechanical Enclosure",
      HeatingSource: "100% Hydronic Heat Recovery from MAN CHP Generator Jackets & Exhaust",
    },
    maintenance: { lastService: "2026-01-14", nextDueHours: 3200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Fuel Storage Farm
  "FUL-BHA-001": {
    assetId: "FUL-BHA-001",
    stationId: "bharati",
    name: "Bulk Kerosene/Diesel Tank Battery & Dispenser",
    category: "FUEL",
    position3D: [16.0, 1.8, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 38000,
    anomalyScore: 0.01,
    readings: {
      volumeLiters: { value: 60000, unit: "L", label: "Total Diesel Storage" },
      fillPercentage: { value: 75.0, unit: "%", label: "Tank Array Fill Level" },
      fuelTemp: { value: -8.5, unit: "°C", label: "Bulk Fuel Temperature" },
      daysRunway: { value: 180, unit: "Days", label: "Calculated Operations Runway" },
    },
    specifications: {
      Capacity: "80,000 Liters in Insulated Modular Steel Cylinders",
      FuelType: "Arctic-Grade Diesel (Jet-A1 Kerosene Cut for -50°C Flow)",
      Containment: "Double Wall with Hydrocarbon Sump Sniffers & Station Feed Pipeline",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Space & Earth Observation Satcom Array (ISRO AGEOS)
  "COM-BHA-AGEOS": {
    assetId: "COM-BHA-AGEOS",
    stationId: "bharati",
    name: "ISRO AGEOS Dual 7.3m Tracking Satellite Radomes",
    category: "COMMS",
    position3D: [14.0, 4.5, -8.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 25000,
    anomalyScore: 0.0,
    readings: {
      satelliteTrack: { value: "Cartosat-3 PASS", unit: "TARGET", label: "Active Tracking Mission" },
      downlinkRate: { value: 105.0, unit: "Mbps", label: "High-Speed X/S Band Downlink" },
      antennaAzimuth: { value: "214.5°", unit: "AZ", label: "Dish Azimuth" },
      antennaElevation: { value: "48.2°", unit: "EL", label: "Dish Elevation" },
      signalStrength: { value: 100, unit: "%", label: "Carrier-to-Noise C/N" },
      dailyPasses: { value: 10, unit: "Passes/day", label: "Polar Satellite Passes Relayed" },
    },
    specifications: {
      Name: "Antarctica Ground Station for Earth Observation Satellites (AGEOS)",
      Operator: "ISRO / National Remote Sensing Centre (NRSC), Commissioned Aug 2013",
      Dishes: "Dual 7.3m High-Gain Az-El Tracking Antennas under Pressurized Radomes",
      Satellites: "Cartosat-1/2/3, Resourcesat-2/2A, Scatsat-1, OceanSat Downlink to NRSC India",
    },
    maintenance: { lastService: "2026-02-12", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  "COM-BHA-001": {
    assetId: "COM-BHA-001",
    stationId: "bharati",
    name: "Station VSAT C-Band Satellite Terminal",
    category: "COMMS",
    position3D: [-6.0, 4.2, -4.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 30000,
    anomalyScore: 0.01,
    readings: {
      linkStatus: { value: "ONLINE", unit: "STATE", label: "NCPOR Goa Direct VSAT Link" },
      snrDb: { value: 16.8, unit: "dB", label: "C-Band Signal-to-Noise Ratio" },
      bandwidthMbps: { value: 12.5, unit: "Mbps", label: "Dedicated IP Data Link Rate" },
    },
    specifications: {
      Dish: "2.4m High-Wind Reinforced Parabolic Reflector",
      Function: "Voice, Data, Video Conferencing, Telemedicine, EPABX Link to NCPOR Headquarters",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 6500, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  // Scientific & Meteorology Observatory
  "AWS-BHA-001": {
    assetId: "AWS-BHA-001",
    stationId: "bharati",
    name: "IMD Automatic Weather Station 10m Lattice Mast",
    category: "SCIENCE",
    position3D: [-16.0, 1.8, -14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {
      ambientTemp: { value: -22.4, unit: "°C", label: "Ambient Air Temperature" },
      windSpeed: { value: 34.1, unit: "km/h", label: "Sustained Wind Velocity" },
      peakGust: { value: 58.0, unit: "km/h", label: "Peak Wind Gust Speed" },
      windDirection: { value: "E (92°)", unit: "DIR", label: "Wind Azimuth" },
      barometricPressure: { value: 988.4, unit: "hPa", label: "Atmospheric Barometric Pressure" },
    },
    specifications: {
      Operator: "India Meteorological Department (IMD), Commissioned 2015",
      Sensors: "Ultrasonic Anemometer, RTD Temperature Shield, Barometric Transducer",
      Height: "10m Freestanding Lattice Mast in Open Larsemann Hills Terrain",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["COM-BHA-001"],
  },

  "SCI-BHA-TERRACE": {
    assetId: "SCI-BHA-TERRACE",
    stationId: "bharati",
    name: "Rooftop Open Scientific Instrument Terrace",
    category: "SCIENCE",
    position3D: [8.0, 4.2, 2.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {
      uvRadiation: { value: 4.2, unit: "UV-Index", label: "Downwelling UV Radiation" },
      aerosolOpticalDepth: { value: 0.04, unit: "AOD", label: "Atmospheric Air Optical Clarity" },
    },
    specifications: {
      Deck: "Third Level Outdoor Platform for Atmospheric Physics & Radiation Sensors",
      Instruments: "Aethelometer, Pyranometer, Spectroradiometer",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 6000, intervalHours: 8760 },
    systemDependencies: ["BLD-BHA-MAIN"],
  },

  // Logistics & Aviation Infrastructure
  "HLP-BHA-001": {
    assetId: "HLP-BHA-001",
    stationId: "bharati",
    name: "Certified Aviation Helideck Platform",
    category: "LOGISTICS",
    position3D: [0.0, 0.6, 18.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 50000,
    anomalyScore: 0.0,
    readings: {
      windsockVector: { value: "34.1 km/h (E)", unit: "WIND", label: "Deck Surface Wind Vector" },
      deckStatus: { value: "CLEAR", unit: "STATE", label: "Operational Deck Condition" },
      floodlights: { value: "STANDBY", unit: "LUX", label: "High-Intensity Approach Beacons" },
    },
    specifications: {
      Deck: "Elevated Structural Steel Helideck with Safety Netting and Tiedowns",
      Rating: "12 Metric Tons Maximum Takeoff Weight (Mil Mi-8 / Ka-32 / Bell 212 / AS350)",
      Function: "Ship-to-Shore Logistics & 100km Inland Fieldwork Helicopter Support",
    },
    maintenance: { lastService: "2026-01-30", nextDueHours: 8500, intervalHours: 8760 },
    systemDependencies: ["AWS-BHA-001"],
  },

  "VEH-BHA-PBULLY": {
    assetId: "VEH-BHA-PBULLY",
    stationId: "bharati",
    name: "PistenBully 300 / 400 Snow Groomer Fleet",
    category: "VEHICLE",
    position3D: [-20.0, 0.8, 10.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 8400,
    anomalyScore: 0.02,
    readings: {
      engineHours: { value: 3420, unit: "Hours", label: "Cumulative Operating Hours" },
      fuelTank: { value: 88, unit: "%", label: "Diesel Tank Level" },
      hydraulicPressure: { value: 240, unit: "bar", label: "Blade & Tiller Hydraulics" },
    },
    specifications: {
      Fleet: "3 Tracked PistenBully 300/400 Heavy Crawler Snowcats",
      Blade: "12-Way Front Hydraulic Dozer Blade & Rear Snow Tiller",
      Engine: "Mercedes-Benz OM460 LA Turbocharged Diesel (400 HP)",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 400, intervalHours: 1000 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "VEH-BHA-TOYOTA": {
    assetId: "VEH-BHA-TOYOTA",
    stationId: "bharati",
    name: "Toyota Arctic Truck Tundra Expedition Pickup",
    category: "VEHICLE",
    position3D: [-24.0, 0.8, 14.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 12000,
    anomalyScore: 0.01,
    readings: {
      odometer: { value: 14200, unit: "km", label: "Ice Sheet Odometer Distance" },
      tirePressurePsi: { value: 4.5, unit: "PSI", label: "Ultra-Low Inflation Snow Pressure" },
    },
    specifications: {
      Vehicle: "44-Inch Ultra-Wide Low-Pressure Balloon Tires on Modified 4x4 Chassis",
      Engine: "V8 Auxiliary Engine Block Pre-Heater",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 900, intervalHours: 2500 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "VEH-BHA-SCOOTER": {
    assetId: "VEH-BHA-SCOOTER",
    stationId: "bharati",
    name: "Polar Expedition Snow Scooters / Mobiles",
    category: "VEHICLE",
    position3D: [-16.0, 0.8, 12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 6500,
    anomalyScore: 0.01,
    readings: {
      scooterStatus: { value: "READY", unit: "STATE", label: "Short-Range Recon Fleet" },
      count: { value: 6, unit: "Units", label: "Active Snow Scooter Inventory" },
    },
    specifications: {
      Type: "Rotax 900 ACE Engine Heavy-Duty Utility Snowmobiles",
      Use: "Short-Range Fieldwork & Fast Personnel Transport across Larsemann Hills",
    },
    maintenance: { lastService: "2026-02-04", nextDueHours: 250, intervalHours: 1000 },
    systemDependencies: ["FUL-BHA-001"],
  },

  "CAMP-BHA-SUMMER": {
    assetId: "CAMP-BHA-SUMMER",
    stationId: "bharati",
    name: "Tented Expedition Summer Camp & Modules",
    category: "LOGISTICS",
    position3D: [24.0, 0.8, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 15000,
    anomalyScore: 0.01,
    readings: {
      capacity: { value: 25, unit: "Crew", label: "Summer Expedition Peak Capacity" },
      tentTemp: { value: 16.5, unit: "°C", label: "Heated Polar Tent Internal Temp" },
    },
    specifications: {
      Tents: "Heavy Weatherhaven Polar Pyramid Tents + Unclad Container Storage",
      Season: "Deployed Dec–Feb to Expand Station Capacity to 72 Expeditioners",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 4000, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001"],
  },
};
