export interface DigitalTwinAsset {
  assetId: string;
  stationId: "maitri" | "bharati";
  name: string;
  category: "POWER" | "FUEL" | "WATER" | "HVAC" | "COMMS" | "SCIENCE" | "BUILDING" | "LOGISTICS" | "SAFETY";
  position3D: [number, number, number];
  rotation3D?: [number, number, number];
  scale3D?: [number, number, number];
  operationalStatus: "RUNNING" | "STOPPED" | "WARNING" | "CRITICAL" | "STANDBY" | "MAINTENANCE";
  healthScore: number;
  failureProbability: number;
  rulHours: number;
  anomalyScore: number;
  readings: Record<string, { value: number | string; unit: string; label: string }>;
  specifications: Record<string, string>;
  maintenance: { lastService: string; nextDueHours: number; intervalHours: number };
  systemDependencies: string[];
}

export const MAITRI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Buildings & Core Habitat
  "BLD-MAI-MAIN": {
    assetId: "BLD-MAI-MAIN",
    stationId: "maitri",
    name: "Maitri Main Station Complex",
    category: "BUILDING",
    position3D: [0, 2.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 18500,
    anomalyScore: 0.03,
    readings: {
      cabinTemp: { value: 21.8, unit: "°C", label: "Internal Living Temperature" },
      relativeHumidity: { value: 38.5, unit: "%", label: "Cabin Relative Humidity" },
      powerDemand: { value: 68.5, unit: "kW", label: "Active Electrical Demand" },
      co2Level: { value: 480, unit: "ppm", label: "Air Quality CO2" },
    },
    specifications: {
      Structure: "2-Story Insulated Modular on Structural Steel Stilts",
      Capacity: "25 Winter-over / 65 Summer Expeditioners",
      Footprint: "2,200 sq. meters",
      Commissioned: "1989 (Indian Antarctic Programme)",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["HVC-MAI-001", "GEN-MAI-001", "WTR-MAI-001"],
  },

  // Power Infrastructure
  "GEN-MAI-001": {
    assetId: "GEN-MAI-001",
    stationId: "maitri",
    name: "Primary Diesel Generator 1",
    category: "POWER",
    position3D: [-14.5, 1.2, -2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7200,
    anomalyScore: 0.05,
    readings: {
      activeLoad: { value: 78.4, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 81.6, unit: "°C", label: "Engine Coolant Temp" },
      rpm: { value: 1500, unit: "RPM", label: "Engine Shaft Speed" },
      oilPressure: { value: 4.8, unit: "bar", label: "Lube Oil Pressure" },
      fuelRate: { value: 18.4, unit: "L/h", label: "Fuel Consumption Rate" },
      vibration: { value: 2.1, unit: "mm/s", label: "Bearing Vibration Level" },
    },
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Exhaust & Coolant Hydronic Loop",
    },
    maintenance: { lastService: "2026-02-01", nextDueHours: 480, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-002": {
    assetId: "GEN-MAI-002",
    stationId: "maitri",
    name: "Primary Diesel Generator 2",
    category: "POWER",
    position3D: [-14.5, 1.2, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.91,
    failureProbability: 0.05,
    rulHours: 6400,
    anomalyScore: 0.08,
    readings: {
      activeLoad: { value: 66.8, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 79.2, unit: "°C", label: "Engine Coolant Temp" },
      rpm: { value: 1500, unit: "RPM", label: "Engine Shaft Speed" },
      oilPressure: { value: 4.6, unit: "bar", label: "Lube Oil Pressure" },
      fuelRate: { value: 16.2, unit: "L/h", label: "Fuel Consumption Rate" },
      vibration: { value: 2.4, unit: "mm/s", label: "Bearing Vibration Level" },
    },
    specifications: {
      Model: "Kirloskar Heavy-Duty Polar Diesel Genset",
      Rating: "125 kVA / 100 kW @ 400V 50Hz",
      Alternator: "Brushless Self-Excited",
      HeatRecovery: "Hydronic Heating Matrix",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 320, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "GEN-MAI-003": {
    assetId: "GEN-MAI-003",
    stationId: "maitri",
    name: "Standby Emergency Generator 3",
    category: "POWER",
    position3D: [-14.5, 1.2, 3.5],
    operationalStatus: "STANDBY",
    healthScore: 1.0,
    failureProbability: 0.01,
    rulHours: 12000,
    anomalyScore: 0.01,
    readings: {
      activeLoad: { value: 0.0, unit: "kW", label: "Electrical Output Load" },
      coolantTemp: { value: 24.5, unit: "°C", label: "Pre-Heater Jacket Temp" },
      rpm: { value: 0, unit: "RPM", label: "Engine Shaft Speed" },
      starterBattery: { value: 27.8, unit: "V", label: "Starter Battery Voltage" },
      readiness: { value: "READY", unit: "STATE", label: "Auto-Crank Status" },
    },
    specifications: {
      Model: "Cummins AMF Emergency Unit",
      Rating: "100 kVA @ 400V",
      AutoStartDelay: "< 15 seconds",
    },
    maintenance: { lastService: "2026-02-10", nextDueHours: 950, intervalHours: 1000 },
    systemDependencies: ["FUL-MAI-001", "SWG-MAI-001"],
  },

  "BAT-MAI-001": {
    assetId: "BAT-MAI-001",
    stationId: "maitri",
    name: "Battery Energy Storage Bank A (BESS)",
    category: "POWER",
    position3D: [-8.5, 1.0, 6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 15400,
    anomalyScore: 0.02,
    readings: {
      soc: { value: 88.5, unit: "%", label: "State of Charge" },
      busVoltage: { value: 402.4, unit: "V", label: "DC Bus Voltage" },
      internalTemp: { value: 21.2, unit: "°C", label: "Cell Array Temperature" },
      chargeRate: { value: 4.5, unit: "kW", label: "Float Charge Power" },
    },
    specifications: {
      Technology: "Lithium Iron Phosphate (LiFePO4) Modular Rack",
      Capacity: "150 kWh / 400 VDC",
      CycleCount: "1,420 cycles",
    },
    maintenance: { lastService: "2026-01-05", nextDueHours: 6200, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "SWG-MAI-001": {
    assetId: "SWG-MAI-001",
    stationId: "maitri",
    name: "Central Microgrid Switchgear",
    category: "POWER",
    position3D: [-11.0, 1.2, 0.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 24000,
    anomalyScore: 0.01,
    readings: {
      frequency: { value: 50.02, unit: "Hz", label: "Grid Synchronized Frequency" },
      totalGeneration: { value: 145.2, unit: "kW", label: "Total Active Generation" },
      totalLoad: { value: 110.0, unit: "kW", label: "Total Station Base Load" },
      powerFactor: { value: 0.94, unit: "PF", label: "System Power Factor" },
    },
    specifications: {
      BusbarRating: "630 A Synchronous Bus",
      ProtectiveRelays: "ABB Microprocessor Digital Protection",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Fuel Storage Farm
  "FUL-MAI-001": {
    assetId: "FUL-MAI-001",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 01",
    category: "FUEL",
    position3D: [12.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 32000,
    anomalyScore: 0.02,
    readings: {
      volumeLiters: { value: 24500, unit: "L", label: "Current Fuel Volume" },
      fillPercent: { value: 81.6, unit: "%", label: "Tank Fill Level" },
      fuelTemp: { value: -12.4, unit: "°C", label: "Internal Fuel Temperature" },
      daysRunway: { value: 65, unit: "Days", label: "Tank Estimated Runway" },
    },
    specifications: {
      Capacity: "30,000 Liters Double-Walled Arctic Steel",
      FuelGrade: "Aviation/Polar Grade Low Pour-Point High-Cetane Diesel",
      Bunding: "110% Spill Containment Berm",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "FUL-MAI-002": {
    assetId: "FUL-MAI-002",
    stationId: "maitri",
    name: "Polar Diesel Storage Tank 02",
    category: "FUEL",
    position3D: [16.0, 1.8, 3.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 34000,
    anomalyScore: 0.01,
    readings: {
      volumeLiters: { value: 20500, unit: "L", label: "Current Fuel Volume" },
      fillPercent: { value: 68.3, unit: "%", label: "Tank Fill Level" },
      fuelTemp: { value: -13.1, unit: "°C", label: "Internal Fuel Temperature" },
      daysRunway: { value: 55, unit: "Days", label: "Tank Estimated Runway" },
    },
    specifications: {
      Capacity: "30,000 Liters Insulated Tank",
      FuelGrade: "Polar Diesel ATF-Grade",
      Bunding: "Secondary Containment Sump",
    },
    maintenance: { lastService: "2026-01-12", nextDueHours: 5400, intervalHours: 8760 },
    systemDependencies: ["PMP-MAI-FUEL"],
  },

  "PMP-MAI-FUEL": {
    assetId: "PMP-MAI-FUEL",
    stationId: "maitri",
    name: "Fuel Transfer Pump Skid",
    category: "FUEL",
    position3D: [14.0, 0.8, 6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.95,
    failureProbability: 0.03,
    rulHours: 8400,
    anomalyScore: 0.04,
    readings: {
      transferRate: { value: 34.5, unit: "L/min", label: "Active Fuel Flow Rate" },
      linePressure: { value: 3.2, unit: "bar", label: "Supply Line Pressure" },
      motorTemp: { value: 38.5, unit: "°C", label: "Pump Motor Temperature" },
    },
    specifications: {
      PumpType: "Positive Displacement Explosion-Proof Gear Pump",
      HeatedTrace: "Electric Trace-Heated Distribution Piping",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 1200, intervalHours: 2500 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  // Lake Priyadarshini Water System
  "PMP-MAI-LAKE": {
    assetId: "PMP-MAI-LAKE",
    stationId: "maitri",
    name: "Lake Priyadarshini Pump House",
    category: "WATER",
    position3D: [-6.0, 0.8, -16.0],
    operationalStatus: "RUNNING",
    healthScore: 0.93,
    failureProbability: 0.04,
    rulHours: 5800,
    anomalyScore: 0.06,
    readings: {
      intakeFlow: { value: 160.0, unit: "L/h", label: "Meltwater Intake Flow" },
      lakeWaterTemp: { value: 1.4, unit: "°C", label: "Sub-Ice Water Temperature" },
      pipeTraceTemp: { value: 8.5, unit: "°C", label: "Heated Pipeline Trace Temp" },
      intakePressure: { value: 4.1, unit: "bar", label: "Intake Line Pressure" },
    },
    specifications: {
      IntakeDepth: "Sub-Ice 4.5m Pier Penetration in Lake Priyadarshini",
      Pipeline: "450m Insulated Electrically Heated Polyethylene Pipe",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 650, intervalHours: 1500 },
    systemDependencies: ["WTR-MAI-001"],
  },

  "WTR-MAI-001": {
    assetId: "WTR-MAI-001",
    stationId: "maitri",
    name: "Priyadarshini Water Treatment Plant",
    category: "WATER",
    position3D: [-5.0, 1.2, -6.0],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 7800,
    anomalyScore: 0.04,
    readings: {
      treatedVolume: { value: 8200, unit: "L", label: "Storage Buffer Volume" },
      filtrationPressure: { value: 3.8, unit: "bar", label: "Filter Differential Pressure" },
      turbidity: { value: 0.18, unit: "NTU", label: "Water Purity Turbidity" },
      dailyConsumption: { value: 1200, unit: "L/day", label: "Station Daily Consumption" },
    },
    specifications: {
      Process: "Dual-Stage Sand Filtration + UV Disinfection + Activated Carbon",
      OutputCapacity: "250 Liters/hour clean potable water",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 1100, intervalHours: 2000 },
    systemDependencies: ["PMP-MAI-LAKE", "BLD-MAI-MAIN"],
  },

  // Scientific, AWS & Comms
  "AWS-MAI-001": {
    assetId: "AWS-MAI-001",
    stationId: "maitri",
    name: "Automatic Weather Station (AWS)",
    category: "SCIENCE",
    position3D: [8.0, 1.5, -12.0],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 22000,
    anomalyScore: 0.01,
    readings: {
      ambientTemp: { value: -25.2, unit: "°C", label: "Ambient Surface Air Temp" },
      windSpeed: { value: 28.5, unit: "km/h", label: "Sustained Wind Velocity" },
      windGust: { value: 42.0, unit: "km/h", label: "Peak Gust Speed" },
      windDirection: { value: "ESE (115°)", unit: "DIR", label: "Wind Azimuth Direction" },
      barometricPressure: { value: 984.2, unit: "hPa", label: "Atmospheric Air Pressure" },
      solarRadiation: { value: 180, unit: "W/m²", label: "Downwelling Solar Flux" },
    },
    specifications: {
      Instrumentation: "Ultrasonic Anemometer, RTD Temp Shield, Barometric Transducer",
      LogRate: "1 Hz sampling with 1-min averaging",
    },
    maintenance: { lastService: "2026-01-08", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["COM-MAI-001"],
  },

  "COM-MAI-001": {
    assetId: "COM-MAI-001",
    stationId: "maitri",
    name: "Ku-Band Satellite Ground Station Radome",
    category: "COMMS",
    position3D: [12.0, 4.2, -7.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.02,
    rulHours: 19500,
    anomalyScore: 0.02,
    readings: {
      signalSnr: { value: 28.4, unit: "dB", label: "Signal-to-Noise Ratio" },
      uplinkThroughput: { value: 12.5, unit: "Mbps", label: "Uplink Data Bandwidth" },
      latency: { value: 242, unit: "ms", label: "GEO Satcom Latency" },
      deIcePower: { value: 3.2, unit: "kW", label: "Radome De-Ice Thermal Power" },
    },
    specifications: {
      Antenna: "3.8m Tracking Dish under Hydrophobic Polar Radome",
      Orbit: "INSAT / GSAT Dedicated Transponder Relay to NCAOR Goa",
    },
    maintenance: { lastService: "2026-01-28", nextDueHours: 4500, intervalHours: 8760 },
    systemDependencies: ["SWG-MAI-001"],
  },

  "HVC-MAI-001": {
    assetId: "HVC-MAI-001",
    stationId: "maitri",
    name: "Central HVAC & Hydronic Thermal Loop",
    category: "HVAC",
    position3D: [5.0, 1.4, -4.5],
    operationalStatus: "RUNNING",
    healthScore: 0.88,
    failureProbability: 0.11,
    rulHours: 2100,
    anomalyScore: 0.28,
    readings: {
      supplyTemp: { value: 68.4, unit: "°C", label: "Hydronic Supply Temp" },
      returnTemp: { value: 52.1, unit: "°C", label: "Hydronic Return Temp" },
      airflowRate: { value: 92.0, unit: "%", label: "Blower Fan Duty Cycle" },
      intakeDelta: { value: -25.2, unit: "°C", label: "Fresh Air Intake Temp" },
    },
    specifications: {
      Type: "Dual Hydronic Circulation Loop with Waste-Heat Recovery Coils",
      AuxiliaryBackup: "45 kW Electric Heating Battery",
    },
    maintenance: { lastService: "2026-01-02", nextDueHours: 120, intervalHours: 1500 },
    systemDependencies: ["GEN-MAI-001", "GEN-MAI-002"],
  },

  "HLP-MAI-001": {
    assetId: "HLP-MAI-001",
    stationId: "maitri",
    name: "Maitri Polar Helipad Deck",
    category: "LOGISTICS",
    position3D: [0.0, 0.4, 15.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 50000,
    anomalyScore: 0.0,
    readings: {
      windCondition: { value: "28.5 km/h", unit: "WIND", label: "Approach Wind Vector" },
      runwayFriction: { value: "GOOD", unit: "SURFACE", label: "Snow Pack Friction Coeff" },
      deckLighting: { value: "ACTIVE", unit: "STATE", label: "Perimeter High-Lux Lighting" },
    },
    specifications: {
      Surface: "Compacted Snow/Ice Reinforced Perimeter Deck",
      DesignHelicopter: "Kamov Ka-32 / Mil Mi-8 Polar Operations",
    },
    maintenance: { lastService: "2026-02-15", nextDueHours: 9000, intervalHours: 10000 },
    systemDependencies: ["AWS-MAI-001"],
  },
};

export const BHARATI_ASSET_REGISTRY: Record<string, DigitalTwinAsset> = {
  // Main Aerodynamic Superstructure
  "BLD-BHA-MAIN": {
    assetId: "BLD-BHA-MAIN",
    stationId: "bharati",
    name: "Bharati Station Superstructure",
    category: "BUILDING",
    position3D: [0, 3.2, 0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 28000,
    anomalyScore: 0.01,
    readings: {
      cabinTemp: { value: 22.4, unit: "°C", label: "Internal Living Quarters Temp" },
      relativeHumidity: { value: 42.0, unit: "%", label: "Indoor Relative Humidity" },
      totalBaseLoad: { value: 135.0, unit: "kW", label: "Station Electrical Load" },
      buildingPressure: { value: "+12", unit: "Pa", label: "Positive Air Ingress Pressure" },
    },
    specifications: {
      Architecture: "3-Story Aerodynamic Faceted Envelope on Heavy Steel Stilts",
      Capacity: "47 Winter-over & Summer Research Scientists",
      Area: "2,500 sq. meters (ISO Shipping Container Modular Integration)",
      Commissioned: "March 2012 (31st Indian Antarctic Expedition)",
    },
    maintenance: { lastService: "2026-01-20", nextDueHours: 6500, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "HVC-BHA-001", "WTR-BHA-001"],
  },

  // Combined Heat & Power (CHP) Generation
  "GEN-BHA-001": {
    assetId: "GEN-BHA-001",
    stationId: "bharati",
    name: "Combined Heat & Power (CHP) Unit 1",
    category: "POWER",
    position3D: [-12.0, 1.6, -1.0],
    operationalStatus: "RUNNING",
    healthScore: 0.97,
    failureProbability: 0.02,
    rulHours: 9200,
    anomalyScore: 0.03,
    readings: {
      electricalPower: { value: 92.4, unit: "kW", label: "Active Electrical Generation" },
      thermalOutput: { value: 112.0, unit: "kW", label: "Captured Hydronic Heat Output" },
      coolantTemp: { value: 80.4, unit: "°C", label: "CHP Jacket Coolant Temp" },
      exhaustTemp: { value: 340.0, unit: "°C", label: "Exhaust Heat Exchanger Inlet" },
      fuelFlowRate: { value: 21.2, unit: "L/h", label: "Fuel Consumption Rate" },
    },
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz 3-Phase",
    },
    maintenance: { lastService: "2026-02-05", nextDueHours: 720, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "GEN-BHA-002": {
    assetId: "GEN-BHA-002",
    stationId: "bharati",
    name: "Combined Heat & Power (CHP) Unit 2",
    category: "POWER",
    position3D: [-12.0, 1.6, 2.5],
    operationalStatus: "RUNNING",
    healthScore: 0.94,
    failureProbability: 0.03,
    rulHours: 8600,
    anomalyScore: 0.05,
    readings: {
      electricalPower: { value: 88.1, unit: "kW", label: "Active Electrical Generation" },
      thermalOutput: { value: 105.5, unit: "kW", label: "Captured Hydronic Heat Output" },
      coolantTemp: { value: 81.2, unit: "°C", label: "CHP Jacket Coolant Temp" },
      fuelFlowRate: { value: 20.4, unit: "L/h", label: "Fuel Consumption Rate" },
    },
    specifications: {
      Genset: "MAN High-Efficiency Industrial CHP Diesel Unit",
      ThermalEfficiency: "Overall Combined Fuel Efficiency > 82%",
      Output: "140 kVA @ 400V 50Hz",
    },
    maintenance: { lastService: "2026-01-25", nextDueHours: 540, intervalHours: 1500 },
    systemDependencies: ["FUL-BHA-001", "SWG-BHA-001", "HVC-BHA-001"],
  },

  "BAT-BHA-001": {
    assetId: "BAT-BHA-001",
    stationId: "bharati",
    name: "Main High-Capacity BESS Array",
    category: "POWER",
    position3D: [-6.5, 1.2, 5.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 18000,
    anomalyScore: 0.01,
    readings: {
      soc: { value: 94.2, unit: "%", label: "State of Charge" },
      dcBusVoltage: { value: 408.0, unit: "V", label: "BESS DC Bus Voltage" },
      temperature: { value: 23.0, unit: "°C", label: "Battery Enclosure Temp" },
      healthCapacity: { value: 99.1, unit: "%", label: "Retained SOH Capacity" },
    },
    specifications: {
      Type: "Industrial LiFePO4 Containerized BESS",
      Capacity: "250 kWh / 400 VDC",
    },
    maintenance: { lastService: "2026-01-15", nextDueHours: 7800, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  "SWG-BHA-001": {
    assetId: "SWG-BHA-001",
    stationId: "bharati",
    name: "Microgrid Synchronous Switchboard",
    category: "POWER",
    position3D: [-9.0, 1.4, 0.5],
    operationalStatus: "RUNNING",
    healthScore: 0.99,
    failureProbability: 0.01,
    rulHours: 35000,
    anomalyScore: 0.01,
    readings: {
      totalGenerationKw: { value: 180.5, unit: "kW", label: "Total Active Power" },
      totalDemandKw: { value: 135.0, unit: "kW", label: "Total Station Consumption" },
      gridHz: { value: 50.01, unit: "Hz", label: "System Frequency" },
      reserveMarginKw: { value: 45.5, unit: "kW", label: "Spinning Reserve Margin" },
    },
    specifications: {
      Automation: "Schneider PLC Microgrid Load Shedder & Frequency Synchronizer",
    },
    maintenance: { lastService: "2026-01-18", nextDueHours: 8200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Coastal Sea-Water & RO System
  "PMP-BHA-SEA": {
    assetId: "PMP-BHA-SEA",
    stationId: "bharati",
    name: "Coastal Sea-Water Pump House",
    category: "WATER",
    position3D: [5.0, 0.6, -18.0],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 8900,
    anomalyScore: 0.03,
    readings: {
      seawaterFlow: { value: 420.0, unit: "L/h", label: "Raw Seawater Intake Flow" },
      seawaterTemp: { value: -1.6, unit: "°C", label: "Prydz Bay Seawater Temp" },
      intakePressure: { value: 5.2, unit: "bar", label: "High-Pressure Delivery" },
      salinityTDS: { value: 34500, unit: "ppm", label: "Seawater Salinity TDS" },
    },
    specifications: {
      Intake: "Submerged Coastal Intake Crib in Prydz Bay (Heated Impeller Housing)",
      SubseaPiping: "Dual Electric Heat-Traced Titanium-Reinforced Lines",
    },
    maintenance: { lastService: "2026-01-22", nextDueHours: 950, intervalHours: 2000 },
    systemDependencies: ["WTR-BHA-001"],
  },

  "WTR-BHA-001": {
    assetId: "WTR-BHA-001",
    stationId: "bharati",
    name: "Reverse Osmosis (RO) Desalination Plant",
    category: "WATER",
    position3D: [3.5, 1.2, -6.5],
    operationalStatus: "RUNNING",
    healthScore: 0.96,
    failureProbability: 0.02,
    rulHours: 9400,
    anomalyScore: 0.02,
    readings: {
      permeateFlow: { value: 185.0, unit: "L/h", label: "Freshwater Production Rate" },
      storageVolume: { value: 12500, unit: "L", label: "Potable Water Reservoir Volume" },
      membranePressure: { value: 58.4, unit: "bar", label: "RO High-Pressure Membrane" },
      productTds: { value: 85, unit: "ppm", label: "Potable Mineralization Purity" },
    },
    specifications: {
      System: "Energy Recovery Seawater Reverse Osmosis (SWRO) with UV Treatment",
      DailyOutput: "4,500 Liters/day pure drinking and service water",
    },
    maintenance: { lastService: "2026-02-02", nextDueHours: 1400, intervalHours: 3000 },
    systemDependencies: ["PMP-BHA-SEA", "BLD-BHA-MAIN"],
  },

  // Fuel Storage Farm
  "FUL-BHA-001": {
    assetId: "FUL-BHA-001",
    stationId: "bharati",
    name: "Bulk Fuel Tank Battery",
    category: "FUEL",
    position3D: [14.0, 1.8, 4.0],
    operationalStatus: "RUNNING",
    healthScore: 0.98,
    failureProbability: 0.01,
    rulHours: 38000,
    anomalyScore: 0.01,
    readings: {
      volumeLiters: { value: 60000, unit: "L", label: "Total Diesel Storage" },
      fillPercentage: { value: 75.0, unit: "%", label: "Tank Array Fill Level" },
      fuelTemp: { value: -8.5, unit: "°C", label: "Bulk Fuel Temperature" },
      daysRunway: { value: 180, unit: "Days", label: "Calculated Operations Runway" },
    },
    specifications: {
      Capacity: "80,000 Liters in Insulated Modular Steel Cylinders",
      FuelType: "Arctic-Grade Diesel (Jet-A1 Kerosene Cut for -50°C Flow)",
      Containment: "Double Wall with Hydrocarbon Sump Sniffers",
    },
    maintenance: { lastService: "2026-01-10", nextDueHours: 7200, intervalHours: 8760 },
    systemDependencies: ["GEN-BHA-001", "GEN-BHA-002"],
  },

  // Space & Earth Observation Satcom Array
  "COM-BHA-001": {
    assetId: "COM-BHA-001",
    stationId: "bharati",
    name: "Dual Tracking Satcom Radomes (ISRO / NRSC)",
    category: "COMMS",
    position3D: [12.5, 4.5, -6.5],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 25000,
    anomalyScore: 0.0,
    readings: {
      satelliteTrack: { value: "Cartosat-3 PASS", unit: "TARGET", label: "Active Tracking Mission" },
      downlinkRate: { value: 105.0, unit: "Mbps", label: "High-Speed X/S Band Downlink" },
      antennaAzimuth: { value: "214.5°", unit: "AZ", label: "Dish Elevation / Azimuth" },
      signalStrength: { value: 100, unit: "%", label: "Carrier-to-Noise C/N" },
    },
    specifications: {
      Dishes: "Dual 7.3m High-Gain Tracking Antennas under Pressurized Radomes",
      Mission: "Polar Orbit Earth Observation Satellite Telemetry & Remote Sensing",
    },
    maintenance: { lastService: "2026-02-12", nextDueHours: 4200, intervalHours: 8760 },
    systemDependencies: ["SWG-BHA-001"],
  },

  // Aviation Helipad Deck
  "HLP-BHA-001": {
    assetId: "HLP-BHA-001",
    stationId: "bharati",
    name: "Certified Aviation Helipad Platform",
    category: "LOGISTICS",
    position3D: [0.0, 0.6, 16.0],
    operationalStatus: "RUNNING",
    healthScore: 1.0,
    failureProbability: 0.0,
    rulHours: 50000,
    anomalyScore: 0.0,
    readings: {
      windsockVector: { value: "34.1 km/h (SE)", unit: "WIND", label: "Deck Surface Wind Vector" },
      deckStatus: { value: "CLEAR", unit: "STATE", label: "Operational Deck Condition" },
      floodlights: { value: "STANDBY", unit: "LUX", label: "High-Intensity Approach Beacons" },
    },
    specifications: {
      Deck: "Elevated Structural Steel Helideck with Safety Netting and Tiedowns",
      Rating: "12 Metric Tons Maximum Takeoff Weight (Mil Mi-8 / Ka-32 / Bell 212)",
    },
    maintenance: { lastService: "2026-01-30", nextDueHours: 8500, intervalHours: 8760 },
    systemDependencies: ["AWS-BHA-001"],
  },
};
